"""Frozen-checkpoint expert-portfolio reproduction for BIG_LOTTO wave 55.

The production environment intentionally does not acquire PyTorch.  Instead,
this adapter consumes a compact, checksummed ledger generated by executing two
frozen high-level portfolio entrypoints with their frozen checkpoint and expert
dependencies.  Every lookup is bound to the pinned full causal prefix.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import date
from functools import lru_cache
from importlib.resources import files
from types import MappingProxyType
from typing import Any, Final, cast

from lottolab.application.legacy_history_native_portfolios import (
    LegacyHistoryDraw,
)
from lottolab.application.strategy_preserving_20_ticket import Ticket

SOURCE_NATIVE_WAVE55_PROTOCOL = "legacy_checkpoint_native_wave55/v1"
DEFAULT_SOURCE_NATIVE_WAVE55_USER_SEED = (
    "biglotto-full-universe-checkpoint-native-wave55-v1"
)
ORTHOGONAL_METHOD_ID = "tools/predict_next_draw.py"
SIX_EXPERT_METHOD_ID = "tools/predict_6expert.py"
SUPPORTED_SOURCE_NATIVE_WAVE55_METHODS = (
    ORTHOGONAL_METHOD_ID,
    SIX_EXPERT_METHOD_ID,
)
SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = MappingProxyType(
    {
        ORTHOGONAL_METHOD_ID: (
            "580580e82f0314145d5d1cc45920879ce6e97c70018b7e1cc16435cb7bd8c6c0"
        ),
        SIX_EXPERT_METHOD_ID: (
            "ff7c2b15f37181e7baf0f42d990c40cc29418a53a550794976fd63a298f927e4"
        ),
    }
)
CHECKPOINT_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = MappingProxyType(
    {
        ORTHOGONAL_METHOD_ID: (
            "ai_lab/ai_models/v3_deep_resonance.pth",
            "ef21497fe396cff4d96dc7a123987f9cb188725900162b435be91cfd7d23712d",
            "eca660b2c3f209bd81c94bae6afa85e5daa703ef",
        ),
        SIX_EXPERT_METHOD_ID: (
            "ai_lab/ai_models/v3_deep_resonance.pth",
            "ef21497fe396cff4d96dc7a123987f9cb188725900162b435be91cfd7d23712d",
            "eca660b2c3f209bd81c94bae6afa85e5daa703ef",
        ),
    }
)
FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = (
    MappingProxyType(
        {
            ORTHOGONAL_METHOD_ID: (
                (
                    "ai_lab/adapter.py",
                    "28a171667eedc6849886f085def0561e12c20e1de2800589cb799a4bb3b58807",
                ),
                (
                    "ai_lab/ai_models/transformer_v2.py",
                    "c2fa21888ee5de7c8a28523792babf91ce3185602ccaf762bafcfc3a86c27583",
                ),
                (
                    "ai_lab/scripts/train_v3.py",
                    "7ba91423549ab8b410d74da6fe8aecf7d877fe69a2aa088c9e313ff80069237f",
                ),
                (
                    "ai_lab/data/real_biglotto.json",
                    "434f31e944e835231813bfed7af8e380f1f286523c29737166d5d7d721fd75a8",
                ),
                (
                    "ai_lab/scripts/orthogonal_portfolio.py",
                    "94b11005b9ea874decd948b400f5b65505e445d4c238bbb78bb905834d75c0a4",
                ),
                (
                    "ai_lab/scripts/structural_ai_predictor.py",
                    "04fa60d978e6d89c79566b3851228ea92d0313157a4b318f4ef3971aac5a94cb",
                ),
                (
                    "lottery_api/models/hpsb_optimizer.py",
                    "cf5cd7d971e8bf2f1854d2196824278de957b3eae3697dff197ab9a3c8b78bcc",
                ),
                (
                    "lottery_api/models/unified_predictor.py",
                    "32d0112c95ce33306002b2f4e13e2c768ff7612c0eb8750cd453cba73575e004",
                ),
            ),
            SIX_EXPERT_METHOD_ID: (
                (
                    "ai_lab/adapter.py",
                    "28a171667eedc6849886f085def0561e12c20e1de2800589cb799a4bb3b58807",
                ),
                (
                    "ai_lab/ai_models/transformer_v2.py",
                    "c2fa21888ee5de7c8a28523792babf91ce3185602ccaf762bafcfc3a86c27583",
                ),
                (
                    "ai_lab/scripts/train_v3.py",
                    "7ba91423549ab8b410d74da6fe8aecf7d877fe69a2aa088c9e313ff80069237f",
                ),
                (
                    "ai_lab/data/real_biglotto.json",
                    "434f31e944e835231813bfed7af8e380f1f286523c29737166d5d7d721fd75a8",
                ),
                (
                    "ai_lab/scripts/six_expert_ensemble.py",
                    "e6800e0bd7d3a2c7099948e405d29d9c5fd2d8787ff80d604ebcdaa960001e76",
                ),
                (
                    "ai_lab/scripts/structural_ai_predictor.py",
                    "04fa60d978e6d89c79566b3851228ea92d0313157a4b318f4ef3971aac5a94cb",
                ),
                (
                    "ai_lab/scripts/graph_predictor.py",
                    "cd70713a5709065ce9841b47591684ba70586a0be0a52a46dbfc3237a4956be9",
                ),
                (
                    "ai_lab/scripts/gap_recovery_predictor.py",
                    "748acbb100009c39cbf0ba68550e0f390b3174cfeebf13b27145e0f534361e8c",
                ),
                (
                    "ai_lab/scripts/tail_number_predictor.py",
                    "e558b0033f138ee3addb3a4f34f403cce2cbd2c95fdab48974ffe9a8b2bd64a8",
                ),
                (
                    "lottery_api/models/hpsb_optimizer.py",
                    "cf5cd7d971e8bf2f1854d2196824278de957b3eae3697dff197ab9a3c8b78bcc",
                ),
                (
                    "lottery_api/models/unified_predictor.py",
                    "32d0112c95ce33306002b2f4e13e2c768ff7612c0eb8750cd453cba73575e004",
                ),
            ),
        }
    )
)
NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = (
    MappingProxyType(
        {
            ORTHOGONAL_METHOD_ID: (
                "THREE_POSITIONAL_EXPERT_TICKETS_STRUCTURAL_AI_"
                "HPSB_DMS_THEN_HYBRID_BALANCE"
            ),
            SIX_EXPERT_METHOD_ID: (
                "SIX_POSITIONAL_EXPERT_TICKETS_STRUCTURAL_AI_HPSB_DMS_"
                "COOCCURRENCE_GRAPH_HYBRID_BALANCE_GAP_RECOVERY_THEN_TAIL"
            ),
        }
    )
)
LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = (
    MappingProxyType(
        {
            ORTHOGONAL_METHOD_ID: "ORTHOGONAL_EXPERT_PORTFOLIO_3BET",
            SIX_EXPERT_METHOD_ID: "SIX_EXPERT_ENSEMBLE_6BET",
        }
    )
)
IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = (
    MappingProxyType(
        {
            ORTHOGONAL_METHOD_ID: (),
            SIX_EXPERT_METHOD_ID: (),
        }
    )
)
NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = MappingProxyType(
    {
        ORTHOGONAL_METHOD_ID: 3,
        SIX_EXPERT_METHOD_ID: 6,
    }
)
SOURCE_CANDIDATE_K_VALUES_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = (
    MappingProxyType(
        {
            ORTHOGONAL_METHOD_ID: (10, 12, 30, 49),
            SIX_EXPERT_METHOD_ID: (10, 12, 15, 30, 49),
        }
    )
)
RANDOM_PROTOCOL_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = MappingProxyType(
    {
        ORTHOGONAL_METHOD_ID: (
            "TORCH_MODEL_EVAL_AND_DETERMINISTIC_EXPERT_SELECTION_NO_RNG"
        ),
        SIX_EXPERT_METHOD_ID: (
            "TAIL_EXPERT_PYTHON_RANDOM_RESET_TO_HISTORY_LENGTH_AFTER_"
            "FIVE_DETERMINISTIC_EXPERTS"
        ),
    }
)
RANDOMNESS_USED_BY_SOURCE_NATIVE_WAVE55_METHOD: Final = MappingProxyType(
    {
        ORTHOGONAL_METHOD_ID: False,
        SIX_EXPERT_METHOD_ID: True,
    }
)

FROZEN_SOURCE_COMMIT = "49a25effa62fc24f40789c16be6f11bdfb41a4a9"
CHECKPOINT_INTRODUCTION_COMMIT = (
    "e56ce9f196342e9d50edc9fd19c42f72c1fa2047"
)
CHECKPOINT_INTRODUCTION_TIME = "2026-02-24T11:02:20+08:00"
CHECKPOINT_INTRODUCTION_LOCAL_DATE = date(2026, 2, 24)
CAUSAL_ELIGIBILITY_RULE = (
    "TARGET_DRAW_DATE_STRICTLY_AFTER_CHECKPOINT_GIT_INTRODUCTION_LOCAL_DATE"
)
PINNED_DATASET_SHA256 = (
    "2f3d711cb97cddabfc6d351b5a639614da60dc3473cc23368711f605e3fe2d6b"
)
LEDGER_RESOURCE_NAME = (
    "biglotto_ai_checkpoint_wave55_ticket_ledger_v1.json"
)
LEDGER_SCHEMA_VERSION = "BIG_LOTTO_AI_CHECKPOINT_WAVE55_TICKET_LEDGER_V1"
LEDGER_FILE_SHA256 = (
    "9281469b90edf4b46b6fb7ae9f4de7c14a26aae077ac95f344207c9b34fc8966"
)
LEDGER_CONTENT_SHA256 = (
    "d0a49cc9d8ed82f7555a56bb08d6fc0470f6cc1a7d65a39734d8a246d092e76b"
)
SOURCE_REFERENCE_RUNTIME = (
    "CPYTHON_3_9_6_TORCH_2_8_0_NUMPY_1_26_2_SCIPY_1_12_0_CPU_"
    "MKLDNN_MODEL_EVAL_TAIL_RANDOM_SEED_HISTORY_LENGTH"
)
MODEL_CONTEXT_DRAW_COUNT = 15
MODEL_CANDIDATE_K = 49
CONTEXT_POLICY = "FULL_STRICT_PREFIX_BEFORE_TARGET"


class LegacyCheckpointNativeWave55Error(ValueError):
    """The request or packaged ticket ledger violates the wave-55 contract."""


class LegacyCheckpointNativeWave55SourceError(
    LegacyCheckpointNativeWave55Error
):
    """A target cannot safely consume a frozen checkpoint ticket."""

    def __init__(self, reason_code: str) -> None:
        super().__init__(reason_code)
        self.reason_code = reason_code


@dataclass(frozen=True, slots=True)
class LegacyCheckpointNativeWave55Request:
    legacy_method_id: str
    target_draw_number: str
    target_draw_date: date
    history: tuple[LegacyHistoryDraw, ...]
    dataset_sha256: str
    replicate_id: int = 0
    user_seed: str | int = DEFAULT_SOURCE_NATIVE_WAVE55_USER_SEED


@dataclass(frozen=True, slots=True)
class LegacyCheckpointNativeWave55Metadata:
    protocol: str
    legacy_method_id: str
    source_sha256: str
    target_draw_number: str
    target_draw_date: str
    replicate_id: int
    user_seed: str | int
    seed_material: str
    seed_digest: str
    seed_integer: int
    random_protocol: str
    randomness_used: bool
    randomness_reproduction: str
    history_draw_count: int
    history_first_draw_number: str
    history_cutoff_draw_number: str
    source_history_order: str
    source_history_order_detail: str
    context_draw_count: int
    context_numbers_sha256: str
    model_context_draw_count: int
    model_context_numbers_sha256: str
    source_candidate_k_values: tuple[int, ...]
    candidate_k: None
    native_ticket_count: int
    native_ticket_count_semantics: str
    native_ticket_order: str
    native_duplicate_ticket_count: int
    combination_count: None
    local_source_configuration: str
    imported_comparators_excluded: tuple[str, ...]
    checkpoint_path: str
    checkpoint_sha256: str
    checkpoint_blob_id: str
    checkpoint_introduction_commit: str
    checkpoint_introduction_time: str
    causal_eligibility_rule: str
    source_reference_runtime: str
    ledger_schema_version: str
    ledger_file_sha256: str
    ledger_content_sha256: str
    ledger_target_index: int
    frozen_support_artifacts: tuple[tuple[str, str], ...]

    def canonical_dict(self) -> dict[str, object]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class LegacyCheckpointNativeWave55Result:
    tickets: tuple[Ticket, ...]
    metadata: LegacyCheckpointNativeWave55Metadata


@dataclass(frozen=True, slots=True)
class _Ledger:
    targets: tuple[str, ...]
    context_sha256: tuple[str, ...]
    tickets_by_method: MappingProxyType[str, tuple[tuple[Ticket, ...], ...]]


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _ticket(value: object) -> Ticket:
    if not isinstance(value, list):
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 ticket must be an array"
        )
    values = cast(list[object], value)
    integer_values = (
        cast(list[int], values)
        if all(type(number) is int for number in values)
        else []
    )
    if (
        len(values) != 6
        or len(integer_values) != 6
        or len(set(values)) != 6
        or integer_values != sorted(integer_values)
        or any(not 1 <= cast(int, number) <= 49 for number in values)
    ):
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 ticket is not a sorted legal ticket"
        )
    return cast(Ticket, tuple(integer_values))


@lru_cache(maxsize=1)
def _load_ledger() -> _Ledger:
    resource = files("lottolab.strategies.data").joinpath(
        LEDGER_RESOURCE_NAME
    )
    raw = resource.read_bytes()
    if hashlib.sha256(raw).hexdigest() != LEDGER_FILE_SHA256:
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 ledger file SHA changed"
        )
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 ledger is invalid JSON"
        ) from exc
    if not isinstance(parsed, dict):
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 ledger must be an object"
        )
    document = cast(dict[str, Any], parsed)
    claimed_content_sha256 = document.pop("ledger_content_sha256", None)
    if (
        claimed_content_sha256 != LEDGER_CONTENT_SHA256
        or hashlib.sha256(_canonical_bytes(document)).hexdigest()
        != LEDGER_CONTENT_SHA256
        or document.get("ledger_schema_version")
        != LEDGER_SCHEMA_VERSION
        or document.get("frozen_source_commit") != FROZEN_SOURCE_COMMIT
        or document.get("dataset_sha256") != PINNED_DATASET_SHA256
        or document.get("artifact_introduction_commit")
        != CHECKPOINT_INTRODUCTION_COMMIT
        or document.get("artifact_introduction_time")
        != CHECKPOINT_INTRODUCTION_TIME
        or document.get("causal_eligibility_rule")
        != CAUSAL_ELIGIBILITY_RULE
        or document.get("context_policy") != CONTEXT_POLICY
        or document.get("model_context_draw_count") != MODEL_CONTEXT_DRAW_COUNT
        or document.get("native_ticket_count_by_method")
        != dict(NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE55_METHOD)
        or document.get("source_sha256_by_method")
        != dict(SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE55_METHOD)
    ):
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 ledger identity changed"
        )
    targets_raw = document.get("target_draw_numbers")
    context_raw = document.get("context_numbers_sha256_by_target")
    tickets_raw = document.get("tickets_by_method")
    if (
        not isinstance(targets_raw, list)
        or not isinstance(context_raw, list)
        or not isinstance(tickets_raw, dict)
    ):
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 ledger layout changed"
        )
    targets_values = cast(list[object], targets_raw)
    context_values = cast(list[object], context_raw)
    if (
        len(targets_values) != 48
        or len(context_values) != 48
        or len(set(targets_values)) != 48
        or any(type(item) is not str or not item for item in targets_values)
        or any(
            type(item) is not str
            or len(item) != 64
            or any(character not in "0123456789abcdef" for character in item)
            for item in context_values
        )
    ):
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 target ledger changed"
        )
    typed_tickets = cast(dict[str, object], tickets_raw)
    if set(typed_tickets) != set(SUPPORTED_SOURCE_NATIVE_WAVE55_METHODS):
        raise LegacyCheckpointNativeWave55Error(
            "packaged wave-55 method set changed"
        )
    by_method: dict[str, tuple[tuple[Ticket, ...], ...]] = {}
    for method_id in SUPPORTED_SOURCE_NATIVE_WAVE55_METHODS:
        method_tickets_raw = typed_tickets[method_id]
        if not isinstance(method_tickets_raw, list):
            raise LegacyCheckpointNativeWave55Error(
                "packaged wave-55 method tickets changed"
            )
        method_portfolios: list[tuple[Ticket, ...]] = []
        for candidate in cast(list[object], method_tickets_raw):
            if not isinstance(candidate, list):
                raise LegacyCheckpointNativeWave55Error(
                    "packaged wave-55 method portfolio changed"
                )
            portfolio = tuple(
                _ticket(ticket)
                for ticket in cast(list[object], candidate)
            )
            if (
                len(portfolio)
                != NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE55_METHOD[method_id]
            ):
                raise LegacyCheckpointNativeWave55Error(
                    "packaged wave-55 native ticket count changed"
                )
            method_portfolios.append(portfolio)
        if len(method_portfolios) != len(targets_values):
            raise LegacyCheckpointNativeWave55Error(
                "packaged wave-55 method ticket count changed"
            )
        by_method[method_id] = tuple(method_portfolios)
    return _Ledger(
        targets=cast(tuple[str, ...], tuple(targets_values)),
        context_sha256=cast(tuple[str, ...], tuple(context_values)),
        tickets_by_method=MappingProxyType(by_method),
    )


def load_legacy_checkpoint_native_wave55_ledger_for_verification() -> _Ledger:
    """Expose the immutable checksummed ledger to contract tests."""

    return _load_ledger()


def _validate_request(
    request: LegacyCheckpointNativeWave55Request,
) -> None:
    if (
        request.legacy_method_id
        not in SUPPORTED_SOURCE_NATIVE_WAVE55_METHODS
    ):
        raise LegacyCheckpointNativeWave55Error(
            "legacy method is outside the wave-55 batch"
        )
    if (
        type(request.target_draw_number) is not str
        or not request.target_draw_number
        or type(request.target_draw_date) is not date
        or type(request.replicate_id) is not int
        or request.replicate_id < 0
        or type(request.user_seed) not in (str, int)
        or request.dataset_sha256 != PINNED_DATASET_SHA256
    ):
        raise LegacyCheckpointNativeWave55Error(
            "invalid frozen checkpoint request identity"
        )
    if request.target_draw_date <= CHECKPOINT_INTRODUCTION_LOCAL_DATE:
        raise LegacyCheckpointNativeWave55SourceError(
            "TARGET_NOT_STRICTLY_AFTER_CHECKPOINT_GIT_INTRODUCTION_LOCAL_DATE"
        )
    if len(request.history) < MODEL_CONTEXT_DRAW_COUNT:
        raise LegacyCheckpointNativeWave55SourceError(
            "AVAILABLE_HISTORY_BELOW_FROZEN_MODEL_CONTEXT"
        )
    seen: set[str] = set()
    for draw in request.history:
        if (
            not draw.draw_number
            or draw.draw_number == request.target_draw_number
            or draw.draw_number in seen
        ):
            raise LegacyCheckpointNativeWave55Error(
                "causal history draw identities are invalid"
            )
        _ticket(list(draw.numbers))
        seen.add(draw.draw_number)


def _full_context_sha256(
    history: tuple[LegacyHistoryDraw, ...],
) -> str:
    return hashlib.sha256(
        json.dumps(
            [list(draw.numbers) for draw in history],
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()


def _model_context_sha256(
    history: tuple[LegacyHistoryDraw, ...],
) -> str:
    return hashlib.sha256(
        json.dumps(
            [
                list(draw.numbers)
                for draw in history[-MODEL_CONTEXT_DRAW_COUNT:]
            ],
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()


def generate_legacy_checkpoint_native_wave55_portfolio(
    request: LegacyCheckpointNativeWave55Request,
) -> LegacyCheckpointNativeWave55Result:
    """Return the exact frozen-runtime ticket for one causal target."""

    _validate_request(request)
    ledger = _load_ledger()
    try:
        target_index = ledger.targets.index(request.target_draw_number)
    except ValueError as exc:
        raise LegacyCheckpointNativeWave55SourceError(
            "TARGET_OUTSIDE_FROZEN_CHECKPOINT_TICKET_LEDGER"
        ) from exc
    context_sha256 = _full_context_sha256(request.history)
    if context_sha256 != ledger.context_sha256[target_index]:
        raise LegacyCheckpointNativeWave55SourceError(
            "FROZEN_MODEL_CONTEXT_IDENTITY_MISMATCH"
        )
    seed_material = "|".join(
        (
            SOURCE_NATIVE_WAVE55_PROTOCOL,
            request.legacy_method_id,
            SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE55_METHOD[
                request.legacy_method_id
            ],
            request.target_draw_number,
            str(request.replicate_id),
            str(request.user_seed),
        )
    )
    seed_digest = hashlib.sha256(
        seed_material.encode("utf-8")
    ).hexdigest()
    checkpoint_path, checkpoint_sha256, checkpoint_blob_id = (
        CHECKPOINT_BY_SOURCE_NATIVE_WAVE55_METHOD[
            request.legacy_method_id
        ]
    )
    tickets = ledger.tickets_by_method[request.legacy_method_id][
        target_index
    ]
    return LegacyCheckpointNativeWave55Result(
        tickets=tickets,
        metadata=LegacyCheckpointNativeWave55Metadata(
            protocol=SOURCE_NATIVE_WAVE55_PROTOCOL,
            legacy_method_id=request.legacy_method_id,
            source_sha256=(
                SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE55_METHOD[
                    request.legacy_method_id
                ]
            ),
            target_draw_number=request.target_draw_number,
            target_draw_date=request.target_draw_date.isoformat(),
            replicate_id=request.replicate_id,
            user_seed=request.user_seed,
            seed_material=seed_material,
            seed_digest=seed_digest,
            seed_integer=int(seed_digest, 16),
            random_protocol=RANDOM_PROTOCOL_BY_SOURCE_NATIVE_WAVE55_METHOD[
                request.legacy_method_id
            ],
            randomness_used=(
                RANDOMNESS_USED_BY_SOURCE_NATIVE_WAVE55_METHOD[
                    request.legacy_method_id
                ]
            ),
            randomness_reproduction=(
                "SOURCE_RUNTIME_LEDGER_EXACT_TICKET_REPLAY"
            ),
            history_draw_count=len(request.history),
            history_first_draw_number=request.history[0].draw_number,
            history_cutoff_draw_number=request.history[-1].draw_number,
            source_history_order="OLDEST_FIRST",
            source_history_order_detail=(
                "DATABASE_NEWEST_FIRST_REVERSED_TO_OLDEST_FIRST_THEN_"
                "STRICT_FULL_PREFIX_BEFORE_TARGET;CHECKPOINT_MODEL_USES_"
                "LAST15_WHILE_OTHER_EXPERTS_MAY_USE_THE_FULL_PREFIX"
            ),
            context_draw_count=len(request.history),
            context_numbers_sha256=context_sha256,
            model_context_draw_count=MODEL_CONTEXT_DRAW_COUNT,
            model_context_numbers_sha256=_model_context_sha256(
                request.history
            ),
            source_candidate_k_values=(
                SOURCE_CANDIDATE_K_VALUES_BY_SOURCE_NATIVE_WAVE55_METHOD[
                    request.legacy_method_id
                ]
            ),
            candidate_k=None,
            native_ticket_count=len(tickets),
            native_ticket_count_semantics=(
                NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE55_METHOD[
                    request.legacy_method_id
                ]
            ),
            native_ticket_order=(
                "FROZEN_SOURCE_EXPERT_POSITION_ORDER_BEFORE_ORDERED_20"
            ),
            native_duplicate_ticket_count=len(tickets) - len(set(tickets)),
            combination_count=None,
            local_source_configuration=(
                LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE55_METHOD[
                    request.legacy_method_id
                ]
            ),
            imported_comparators_excluded=(
                IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE55_METHOD[
                    request.legacy_method_id
                ]
            ),
            checkpoint_path=checkpoint_path,
            checkpoint_sha256=checkpoint_sha256,
            checkpoint_blob_id=checkpoint_blob_id,
            checkpoint_introduction_commit=(
                CHECKPOINT_INTRODUCTION_COMMIT
            ),
            checkpoint_introduction_time=CHECKPOINT_INTRODUCTION_TIME,
            causal_eligibility_rule=CAUSAL_ELIGIBILITY_RULE,
            source_reference_runtime=SOURCE_REFERENCE_RUNTIME,
            ledger_schema_version=LEDGER_SCHEMA_VERSION,
            ledger_file_sha256=LEDGER_FILE_SHA256,
            ledger_content_sha256=LEDGER_CONTENT_SHA256,
            ledger_target_index=target_index,
            frozen_support_artifacts=(
                FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE55_METHOD[
                    request.legacy_method_id
                ]
            ),
        ),
    )


__all__ = [
    "CAUSAL_ELIGIBILITY_RULE",
    "CHECKPOINT_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "CHECKPOINT_INTRODUCTION_COMMIT",
    "CHECKPOINT_INTRODUCTION_LOCAL_DATE",
    "CHECKPOINT_INTRODUCTION_TIME",
    "CONTEXT_POLICY",
    "DEFAULT_SOURCE_NATIVE_WAVE55_USER_SEED",
    "FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "LEDGER_CONTENT_SHA256",
    "LEDGER_FILE_SHA256",
    "LEDGER_RESOURCE_NAME",
    "LEDGER_SCHEMA_VERSION",
    "LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "MODEL_CANDIDATE_K",
    "MODEL_CONTEXT_DRAW_COUNT",
    "NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "ORTHOGONAL_METHOD_ID",
    "PINNED_DATASET_SHA256",
    "RANDOMNESS_USED_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "RANDOM_PROTOCOL_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "SIX_EXPERT_METHOD_ID",
    "SOURCE_CANDIDATE_K_VALUES_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "SOURCE_NATIVE_WAVE55_PROTOCOL",
    "SOURCE_REFERENCE_RUNTIME",
    "SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE55_METHOD",
    "SUPPORTED_SOURCE_NATIVE_WAVE55_METHODS",
    "LegacyCheckpointNativeWave55Error",
    "LegacyCheckpointNativeWave55Metadata",
    "LegacyCheckpointNativeWave55Request",
    "LegacyCheckpointNativeWave55Result",
    "LegacyCheckpointNativeWave55SourceError",
    "generate_legacy_checkpoint_native_wave55_portfolio",
    "load_legacy_checkpoint_native_wave55_ledger_for_verification",
]
