"""Frozen HPSB-V2 native-ticket reproduction for BIG_LOTTO wave 57.

The production package does not acquire the legacy numerical stack.  This
adapter consumes a compact checksummed ledger generated by executing the
frozen public ``predict_hpsb_v2`` entrypoint for every target against its
strictly earlier history prefix.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import date
from functools import lru_cache
from importlib.resources import files
from types import MappingProxyType
from typing import Any, Final, cast

from lottolab.application.legacy_history_native_portfolios import (
    LegacyHistoryDraw,
)
from lottolab.application.strategy_preserving_20_ticket import Ticket

SOURCE_NATIVE_WAVE57_PROTOCOL = "legacy_hpsb_native_wave57/v1"
DEFAULT_SOURCE_NATIVE_WAVE57_USER_SEED = (
    "biglotto-full-universe-hpsb-native-wave57-v1"
)
HPSB_METHOD_ID = "lottery_api/models/hpsb_optimizer.py"
ENSEMBLE_ALIAS_METHOD_ID = "lottery_api/models/ensemble_predictor.py"
SUPPORTED_SOURCE_NATIVE_WAVE57_METHODS = (HPSB_METHOD_ID,)
AUDITED_SOURCE_NATIVE_WAVE57_METHODS = (
    HPSB_METHOD_ID,
    ENSEMBLE_ALIAS_METHOD_ID,
)
SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = MappingProxyType(
    {
        HPSB_METHOD_ID: (
            "cf5cd7d971e8bf2f1854d2196824278de957b3eae3697dff197ab9a3c8b78bcc"
        ),
        ENSEMBLE_ALIAS_METHOD_ID: (
            "c66ab4e86aada5072cf1cd2fba3633c9b5510c7431c7e35e1a0db02c81c3f1ac"
        ),
    }
)
FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = (
    MappingProxyType(
        {
            HPSB_METHOD_ID: (
                (
                    "lottery_api/models/unified_predictor.py",
                    "32d0112c95ce33306002b2f4e13e2c768ff7612c0eb8750cd453cba73575e004",
                ),
            ),
            ENSEMBLE_ALIAS_METHOD_ID: (
                (
                    "lottery_api/models/hpsb_optimizer.py",
                    "cf5cd7d971e8bf2f1854d2196824278de957b3eae3697dff197ab9a3c8b78bcc",
                ),
                (
                    "lottery_api/models/unified_predictor.py",
                    "32d0112c95ce33306002b2f4e13e2c768ff7612c0eb8750cd453cba73575e004",
                ),
                (
                    "ai_lab/adapter.py",
                    "28a171667eedc6849886f085def0561e12c20e1de2800589cb799a4bb3b58807",
                ),
            ),
        }
    )
)
NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = (
    MappingProxyType(
        {
            HPSB_METHOD_ID: (
                "ONE_POSITIONAL_HPSB_V2_DYNAMIC_METHOD_SELECTION_TICKET"
            ),
            ENSEMBLE_ALIAS_METHOD_ID: (
                "ONE_POSITIONAL_DEFAULT_ENSEMBLE_TICKET_WITH_UNPATCHED_"
                "UNSUPPORTED_TRANSFORMER_V3_RAW_FALLBACK_TO_HPSB_DMS"
            ),
        }
    )
)
LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = (
    MappingProxyType(
        {
            HPSB_METHOD_ID: "PREDICT_HPSB_V2_DEFAULT_AUDIT_WINDOW_15",
            ENSEMBLE_ALIAS_METHOD_ID: (
                "PREDICT_ENSEMBLE_DEFAULT_AI_WEIGHT_0_4_WITHOUT_CALLING_"
                "LOCAL_PATCH_AI_ADAPTER"
            ),
        }
    )
)
IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = (
    MappingProxyType(
        {
            HPSB_METHOD_ID: (),
            ENSEMBLE_ALIAS_METHOD_ID: (),
        }
    )
)
NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = (
    MappingProxyType(
        {
            HPSB_METHOD_ID: 1,
            ENSEMBLE_ALIAS_METHOD_ID: 1,
        }
    )
)
SOURCE_CANDIDATE_K_VALUES_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = (
    MappingProxyType(
        {
            HPSB_METHOD_ID: (49,),
            ENSEMBLE_ALIAS_METHOD_ID: (49,),
        }
    )
)
RANDOM_PROTOCOL_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = MappingProxyType(
    {
        HPSB_METHOD_ID: (
            "STATISTICAL_SUBMETHOD_RESETS_PYTHON_RANDOM_TO_HISTORY_LENGTH;"
            "OTHER_DYNAMIC_SELECTION_SUBMETHODS_ARE_DETERMINISTIC"
        ),
        ENSEMBLE_ALIAS_METHOD_ID: (
            "DELEGATED_HPSB_STATISTICAL_SUBMETHOD_RESETS_PYTHON_RANDOM_"
            "TO_HISTORY_LENGTH"
        ),
    }
)
RANDOMNESS_USED_BY_SOURCE_NATIVE_WAVE57_METHOD: Final = MappingProxyType(
    {
        HPSB_METHOD_ID: True,
        ENSEMBLE_ALIAS_METHOD_ID: True,
    }
)

FROZEN_SOURCE_COMMIT = "49a25effa62fc24f40789c16be6f11bdfb41a4a9"
PINNED_DATASET_SHA256 = (
    "2f3d711cb97cddabfc6d351b5a639614da60dc3473cc23368711f605e3fe2d6b"
)
LEDGER_RESOURCE_NAME = "biglotto_hpsb_wave57_ticket_ledger_v1.json"
LEDGER_SCHEMA_VERSION = "BIG_LOTTO_HPSB_WAVE57_TICKET_LEDGER_V1"
LEDGER_FILE_SHA256 = (
    "5120f4cf4928eb843c4b1a29ccfe913692bcf34398308d0c89bcde66527f1e45"
)
LEDGER_CONTENT_SHA256 = (
    "f014535c4befa3598a408bf0a05b1b81e11736c6bb57357f71161c8ab70de8c5"
)
SOURCE_REFERENCE_RUNTIME = (
    "CPYTHON_3_9_6_NUMPY_1_26_2_SCIPY_1_12_0_HPSB_V2_DMS_"
    "STATISTICAL_RANDOM_SEED_HISTORY_LENGTH"
)
MODEL_CANDIDATE_K = 49
CONTEXT_POLICY = "FULL_STRICT_PREFIX_BEFORE_TARGET"
CAUSAL_ELIGIBILITY_RULE = (
    "TARGET_USES_ONLY_THE_FULL_STRICTLY_EARLIER_DRAW_PREFIX"
)


class LegacyHpsbNativeWave57Error(ValueError):
    """The request or packaged ticket ledger violates the wave-57 contract."""


class LegacyHpsbNativeWave57SourceError(LegacyHpsbNativeWave57Error):
    """A target cannot safely consume its frozen native ticket."""

    def __init__(self, reason_code: str) -> None:
        super().__init__(reason_code)
        self.reason_code = reason_code


@dataclass(frozen=True, slots=True)
class LegacyHpsbNativeWave57Request:
    legacy_method_id: str
    target_draw_number: str
    target_draw_date: date
    history: tuple[LegacyHistoryDraw, ...]
    dataset_sha256: str
    replicate_id: int = 0
    user_seed: str | int = DEFAULT_SOURCE_NATIVE_WAVE57_USER_SEED


@dataclass(frozen=True, slots=True)
class LegacyHpsbNativeWave57Metadata:
    protocol: str
    legacy_method_id: str
    source_sha256: str
    target_draw_number: str
    target_draw_date: str
    replicate_id: int
    user_seed: str | int
    seed_material: str
    seed_digest: str
    seed_integer: int
    random_protocol: str
    randomness_used: bool
    randomness_reproduction: str
    history_draw_count: int
    history_first_draw_number: str | None
    history_cutoff_draw_number: str | None
    source_history_order: str
    source_history_order_detail: str
    context_draw_count: int
    context_numbers_sha256: str
    source_candidate_k_values: tuple[int, ...]
    candidate_k: None
    native_ticket_count: int
    native_ticket_count_semantics: str
    native_ticket_order: str
    native_duplicate_ticket_count: int
    combination_count: None
    local_source_configuration: str
    imported_comparators_excluded: tuple[str, ...]
    causal_eligibility_rule: str
    source_reference_runtime: str
    ledger_schema_version: str
    ledger_file_sha256: str
    ledger_content_sha256: str
    ledger_target_index: int
    frozen_support_artifacts: tuple[tuple[str, str], ...]

    def canonical_dict(self) -> dict[str, object]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class LegacyHpsbNativeWave57Result:
    tickets: tuple[Ticket, ...]
    metadata: LegacyHpsbNativeWave57Metadata


@dataclass(frozen=True, slots=True)
class _Ledger:
    targets: tuple[str, ...]
    context_sha256: tuple[str, ...]
    tickets_by_method: MappingProxyType[str, tuple[tuple[Ticket, ...], ...]]


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _ticket(value: object) -> Ticket:
    if not isinstance(value, list):
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 ticket must be an array"
        )
    values = cast(list[object], value)
    integers = (
        cast(list[int], values)
        if all(type(number) is int for number in values)
        else []
    )
    if (
        len(integers) != 6
        or integers != sorted(integers)
        or len(set(integers)) != 6
        or any(not 1 <= number <= 49 for number in integers)
    ):
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 ticket is not a sorted legal ticket"
        )
    return cast(Ticket, tuple(integers))


@lru_cache(maxsize=1)
def _load_ledger() -> _Ledger:
    resource = files("lottolab.strategies.data").joinpath(
        LEDGER_RESOURCE_NAME
    )
    raw = resource.read_bytes()
    if hashlib.sha256(raw).hexdigest() != LEDGER_FILE_SHA256:
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 ledger file SHA changed"
        )
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 ledger is invalid JSON"
        ) from exc
    if not isinstance(parsed, dict):
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 ledger must be an object"
        )
    document = cast(dict[str, Any], parsed)
    claimed_content_sha256 = document.pop("ledger_content_sha256", None)
    expected_source_hashes = {
        method_id: SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE57_METHOD[method_id]
        for method_id in SUPPORTED_SOURCE_NATIVE_WAVE57_METHODS
    }
    expected_native_counts = {
        method_id: NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE57_METHOD[
            method_id
        ]
        for method_id in SUPPORTED_SOURCE_NATIVE_WAVE57_METHODS
    }
    if (
        claimed_content_sha256 != LEDGER_CONTENT_SHA256
        or hashlib.sha256(_canonical_bytes(document)).hexdigest()
        != LEDGER_CONTENT_SHA256
        or document.get("ledger_schema_version")
        != LEDGER_SCHEMA_VERSION
        or document.get("frozen_source_commit") != FROZEN_SOURCE_COMMIT
        or document.get("dataset_sha256") != PINNED_DATASET_SHA256
        or document.get("causal_eligibility_rule")
        != CAUSAL_ELIGIBILITY_RULE
        or document.get("context_policy") != CONTEXT_POLICY
        or document.get("native_ticket_count_by_method")
        != expected_native_counts
        or document.get("source_sha256_by_method")
        != expected_source_hashes
    ):
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 ledger identity changed"
        )
    targets_raw = document.get("target_draw_numbers")
    contexts_raw = document.get("context_numbers_sha256_by_target")
    tickets_raw = document.get("tickets_by_method")
    if (
        not isinstance(targets_raw, list)
        or not isinstance(contexts_raw, list)
        or not isinstance(tickets_raw, dict)
    ):
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 ledger layout changed"
        )
    targets = cast(list[object], targets_raw)
    contexts = cast(list[object], contexts_raw)
    if (
        len(targets) != 2149
        or len(contexts) != 2149
        or len(set(targets)) != 2149
        or any(type(item) is not str or not item for item in targets)
        or any(
            type(item) is not str
            or len(item) != 64
            or any(character not in "0123456789abcdef" for character in item)
            for item in contexts
        )
    ):
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 target ledger changed"
        )
    typed_tickets = cast(dict[str, object], tickets_raw)
    if set(typed_tickets) != set(SUPPORTED_SOURCE_NATIVE_WAVE57_METHODS):
        raise LegacyHpsbNativeWave57Error(
            "packaged wave-57 method set changed"
        )
    by_method: dict[str, tuple[tuple[Ticket, ...], ...]] = {}
    for method_id in SUPPORTED_SOURCE_NATIVE_WAVE57_METHODS:
        rows_raw = typed_tickets[method_id]
        if not isinstance(rows_raw, list):
            raise LegacyHpsbNativeWave57Error(
                "packaged wave-57 ticket sequence changed"
            )
        rows: list[tuple[Ticket, ...]] = []
        for candidate in cast(list[object], rows_raw):
            if not isinstance(candidate, list):
                raise LegacyHpsbNativeWave57Error(
                    "packaged wave-57 portfolio changed"
                )
            portfolio = tuple(
                _ticket(ticket)
                for ticket in cast(list[object], candidate)
            )
            if len(portfolio) != 1:
                raise LegacyHpsbNativeWave57Error(
                    "packaged wave-57 native ticket count changed"
                )
            rows.append(portfolio)
        if len(rows) != len(targets):
            raise LegacyHpsbNativeWave57Error(
                "packaged wave-57 method target count changed"
            )
        by_method[method_id] = tuple(rows)
    return _Ledger(
        targets=cast(tuple[str, ...], tuple(targets)),
        context_sha256=cast(tuple[str, ...], tuple(contexts)),
        tickets_by_method=MappingProxyType(by_method),
    )


def load_legacy_hpsb_native_wave57_ledger_for_verification() -> _Ledger:
    """Expose the immutable checksummed ledger to verification code."""

    return _load_ledger()


def _validate_request(request: LegacyHpsbNativeWave57Request) -> None:
    if request.legacy_method_id not in SUPPORTED_SOURCE_NATIVE_WAVE57_METHODS:
        raise LegacyHpsbNativeWave57Error(
            "legacy method is outside the executable wave-57 batch"
        )
    if (
        type(request.target_draw_number) is not str
        or not request.target_draw_number
        or type(request.target_draw_date) is not date
        or type(request.replicate_id) is not int
        or request.replicate_id < 0
        or type(request.user_seed) not in (str, int)
        or type(request.dataset_sha256) is not str or not request.dataset_sha256
    ):
        raise LegacyHpsbNativeWave57Error(
            "invalid frozen HPSB request identity"
        )
    seen: set[str] = set()
    for draw in request.history:
        if (
            not draw.draw_number
            or draw.draw_number == request.target_draw_number
            or draw.draw_number in seen
        ):
            raise LegacyHpsbNativeWave57Error(
                "causal history draw identities are invalid"
            )
        _ticket(list(draw.numbers))
        seen.add(draw.draw_number)


def _full_context_sha256(
    history: tuple[LegacyHistoryDraw, ...],
) -> str:
    return hashlib.sha256(
        json.dumps(
            [list(draw.numbers) for draw in history],
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()


def generate_legacy_hpsb_native_wave57_portfolio(
    request: LegacyHpsbNativeWave57Request,
) -> LegacyHpsbNativeWave57Result:
    """Return one exact frozen-runtime HPSB-V2 ticket."""

    _validate_request(request)
    ledger = _load_ledger()
    try:
        target_index = ledger.targets.index(request.target_draw_number)
    except ValueError as exc:
        raise LegacyHpsbNativeWave57SourceError(
            "TARGET_OUTSIDE_FROZEN_HPSB_TICKET_LEDGER"
        ) from exc
    context_sha256 = _full_context_sha256(request.history)
    if context_sha256 != ledger.context_sha256[target_index]:
        raise LegacyHpsbNativeWave57SourceError(
            "FROZEN_HPSB_FULL_PREFIX_CONTEXT_MISMATCH"
        )
    seed_material = f"random.seed({len(request.history)})"
    seed_digest = hashlib.sha256(
        seed_material.encode("utf-8")
    ).hexdigest()
    tickets = ledger.tickets_by_method[request.legacy_method_id][target_index]
    return LegacyHpsbNativeWave57Result(
        tickets=tickets,
        metadata=LegacyHpsbNativeWave57Metadata(
            protocol=SOURCE_NATIVE_WAVE57_PROTOCOL,
            legacy_method_id=request.legacy_method_id,
            source_sha256=SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE57_METHOD[
                request.legacy_method_id
            ],
            target_draw_number=request.target_draw_number,
            target_draw_date=request.target_draw_date.isoformat(),
            replicate_id=request.replicate_id,
            user_seed=request.user_seed,
            seed_material=seed_material,
            seed_digest=seed_digest,
            seed_integer=len(request.history),
            random_protocol=RANDOM_PROTOCOL_BY_SOURCE_NATIVE_WAVE57_METHOD[
                request.legacy_method_id
            ],
            randomness_used=RANDOMNESS_USED_BY_SOURCE_NATIVE_WAVE57_METHOD[
                request.legacy_method_id
            ],
            randomness_reproduction=(
                "SOURCE_RUNTIME_LEDGER_EXACT_TICKET_REPLAY"
            ),
            history_draw_count=len(request.history),
            history_first_draw_number=(
                request.history[0].draw_number if request.history else None
            ),
            history_cutoff_draw_number=(
                request.history[-1].draw_number if request.history else None
            ),
            source_history_order="OLDEST_FIRST",
            source_history_order_detail=(
                "DATABASE_OLDEST_FIRST_FULL_STRICT_PREFIX_BEFORE_TARGET"
            ),
            context_draw_count=len(request.history),
            context_numbers_sha256=context_sha256,
            source_candidate_k_values=(
                SOURCE_CANDIDATE_K_VALUES_BY_SOURCE_NATIVE_WAVE57_METHOD[
                    request.legacy_method_id
                ]
            ),
            candidate_k=None,
            native_ticket_count=len(tickets),
            native_ticket_count_semantics=(
                NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE57_METHOD[
                    request.legacy_method_id
                ]
            ),
            native_ticket_order=(
                "FROZEN_SOURCE_SINGLE_POSITION_BEFORE_ORDERED_20"
            ),
            native_duplicate_ticket_count=0,
            combination_count=None,
            local_source_configuration=(
                LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE57_METHOD[
                    request.legacy_method_id
                ]
            ),
            imported_comparators_excluded=(
                IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE57_METHOD[
                    request.legacy_method_id
                ]
            ),
            causal_eligibility_rule=CAUSAL_ELIGIBILITY_RULE,
            source_reference_runtime=SOURCE_REFERENCE_RUNTIME,
            ledger_schema_version=LEDGER_SCHEMA_VERSION,
            ledger_file_sha256=LEDGER_FILE_SHA256,
            ledger_content_sha256=LEDGER_CONTENT_SHA256,
            ledger_target_index=target_index,
            frozen_support_artifacts=(
                FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE57_METHOD[
                    request.legacy_method_id
                ]
            ),
        ),
    )


__all__ = [
    "AUDITED_SOURCE_NATIVE_WAVE57_METHODS",
    "CAUSAL_ELIGIBILITY_RULE",
    "CONTEXT_POLICY",
    "DEFAULT_SOURCE_NATIVE_WAVE57_USER_SEED",
    "ENSEMBLE_ALIAS_METHOD_ID",
    "FROZEN_SOURCE_COMMIT",
    "FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "HPSB_METHOD_ID",
    "IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "LEDGER_CONTENT_SHA256",
    "LEDGER_FILE_SHA256",
    "LEDGER_RESOURCE_NAME",
    "LEDGER_SCHEMA_VERSION",
    "LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "MODEL_CANDIDATE_K",
    "NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "PINNED_DATASET_SHA256",
    "RANDOMNESS_USED_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "RANDOM_PROTOCOL_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "SOURCE_CANDIDATE_K_VALUES_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "SOURCE_NATIVE_WAVE57_PROTOCOL",
    "SOURCE_REFERENCE_RUNTIME",
    "SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE57_METHOD",
    "SUPPORTED_SOURCE_NATIVE_WAVE57_METHODS",
    "LegacyHpsbNativeWave57Error",
    "LegacyHpsbNativeWave57Metadata",
    "LegacyHpsbNativeWave57Request",
    "LegacyHpsbNativeWave57Result",
    "LegacyHpsbNativeWave57SourceError",
    "generate_legacy_hpsb_native_wave57_portfolio",
    "load_legacy_hpsb_native_wave57_ledger_for_verification",
]
