"""Frozen-checkpoint ticket reproduction for BIG_LOTTO wave 44.

The production environment intentionally does not acquire PyTorch.  Instead,
this adapter consumes a compact, checksummed ledger generated by executing the
three frozen predictor classes with their frozen checkpoints.  Every lookup is
bound to the pinned database and the exact 15-draw model input.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import date
from functools import lru_cache
from importlib.resources import files
from types import MappingProxyType
from typing import Any, Final, cast

from lottolab.application.legacy_history_native_portfolios import (
    LegacyHistoryDraw,
)
from lottolab.application.strategy_preserving_20_ticket import Ticket

SOURCE_NATIVE_WAVE44_PROTOCOL = "legacy_checkpoint_native_wave44/v1"
DEFAULT_SOURCE_NATIVE_WAVE44_USER_SEED = (
    "biglotto-full-universe-checkpoint-native-wave44-v1"
)
BENCHMARK_AI_METHOD_ID = "ai_lab/scripts/benchmark_ai.py"
BENCHMARK_AI_ZDP_METHOD_ID = "ai_lab/scripts/benchmark_ai_zdp.py"
BENCHMARK_V3_METHOD_ID = "ai_lab/scripts/benchmark_v3.py"
SUPPORTED_SOURCE_NATIVE_WAVE44_METHODS = (
    BENCHMARK_AI_METHOD_ID,
    BENCHMARK_AI_ZDP_METHOD_ID,
    BENCHMARK_V3_METHOD_ID,
)
SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE44_METHOD: Final = MappingProxyType(
    {
        BENCHMARK_AI_METHOD_ID: (
            "85899ce88ef2599f69dab01e4e8e61d225fa2d740fdd4dde32d3b342b5235c95"
        ),
        BENCHMARK_AI_ZDP_METHOD_ID: (
            "920da47e971626dad619f5ce9aff5887e9b6afffb6d5728b565c614dd2a7e3aa"
        ),
        BENCHMARK_V3_METHOD_ID: (
            "0fe7603f150e4c103655c75f8e2f13ae8ed53ada850ee9e181450619d4dad4c7"
        ),
    }
)
CHECKPOINT_BY_SOURCE_NATIVE_WAVE44_METHOD: Final = MappingProxyType(
    {
        BENCHMARK_AI_METHOD_ID: (
            "ai_lab/ai_models/finetuned_best.pth",
            "fbfa05942f6b81ba2cf1da06ef984aaea4693ff681dde2b6aa0c5603f1d198be",
            "1976acf1ca3b277cc39242181df151b62b03523e",
        ),
        BENCHMARK_AI_ZDP_METHOD_ID: (
            "ai_lab/ai_models/finetuned_best.pth",
            "fbfa05942f6b81ba2cf1da06ef984aaea4693ff681dde2b6aa0c5603f1d198be",
            "1976acf1ca3b277cc39242181df151b62b03523e",
        ),
        BENCHMARK_V3_METHOD_ID: (
            "ai_lab/ai_models/v3_deep_resonance.pth",
            "ef21497fe396cff4d96dc7a123987f9cb188725900162b435be91cfd7d23712d",
            "eca660b2c3f209bd81c94bae6afa85e5daa703ef",
        ),
    }
)
FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE44_METHOD: Final = (
    MappingProxyType(
        {
            BENCHMARK_AI_METHOD_ID: (
                (
                    "ai_lab/ai_models/transformer_v1.py",
                    "c2cfd39d9de750f52399993efd8415fc327acfbe1645b58940c42bdf29eea1c4",
                ),
                (
                    "ai_lab/scripts/train_transformer.py",
                    "9520155ca8f2a5dbf4796d5ac4845c9f6e16b7251f87c111a6a1989bd16929ff",
                ),
                (
                    "ai_lab/scripts/finetune_transformer.py",
                    "839468c37b7c8c1a893f86228b135866f5a93da6188c5b750182e5e311f29fa0",
                ),
                (
                    "ai_lab/data/real_biglotto.json",
                    "434f31e944e835231813bfed7af8e380f1f286523c29737166d5d7d721fd75a8",
                ),
            ),
            BENCHMARK_AI_ZDP_METHOD_ID: (
                (
                    "ai_lab/ai_models/transformer_v1.py",
                    "c2cfd39d9de750f52399993efd8415fc327acfbe1645b58940c42bdf29eea1c4",
                ),
                (
                    "ai_lab/scripts/train_transformer.py",
                    "9520155ca8f2a5dbf4796d5ac4845c9f6e16b7251f87c111a6a1989bd16929ff",
                ),
                (
                    "ai_lab/scripts/finetune_transformer.py",
                    "839468c37b7c8c1a893f86228b135866f5a93da6188c5b750182e5e311f29fa0",
                ),
                (
                    "ai_lab/data/real_biglotto.json",
                    "434f31e944e835231813bfed7af8e380f1f286523c29737166d5d7d721fd75a8",
                ),
            ),
            BENCHMARK_V3_METHOD_ID: (
                (
                    "ai_lab/ai_models/transformer_v2.py",
                    "c2fa21888ee5de7c8a28523792babf91ce3185602ccaf762bafcfc3a86c27583",
                ),
                (
                    "ai_lab/scripts/train_v3.py",
                    "7ba91423549ab8b410d74da6fe8aecf7d877fe69a2aa088c9e313ff80069237f",
                ),
                (
                    "ai_lab/data/real_biglotto.json",
                    "434f31e944e835231813bfed7af8e380f1f286523c29737166d5d7d721fd75a8",
                ),
            ),
        }
    )
)
NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE44_METHOD: Final = (
    MappingProxyType(
        {
            BENCHMARK_AI_METHOD_ID: (
                "ONE_FROZEN_CHECKPOINT_TRANSFORMER_TOP6_TICKET"
            ),
            BENCHMARK_AI_ZDP_METHOD_ID: (
                "ONE_FROZEN_CHECKPOINT_TRANSFORMER_TOP6_ZONE_CAPPED_TICKET"
            ),
            BENCHMARK_V3_METHOD_ID: (
                "ONE_FROZEN_CHECKPOINT_U_HPE_V3_TOP6_ZONE_CAPPED_TICKET"
            ),
        }
    )
)
LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE44_METHOD: Final = (
    MappingProxyType(
        {
            BENCHMARK_AI_METHOD_ID: "TRANSFORMER_AI_LAB",
            BENCHMARK_AI_ZDP_METHOD_ID: "TRANSFORMER_PLUS_ZDP",
            BENCHMARK_V3_METHOD_ID: "U_HPE_V3_DEEP_RESONANCE",
        }
    )
)
IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE44_METHOD: Final = (
    MappingProxyType(
        {
            BENCHMARK_AI_METHOD_ID: ("DMS_SOTA_BASELINE",),
            BENCHMARK_AI_ZDP_METHOD_ID: (
                "DMS_SOTA_BASELINE",
                "TRANSFORMER_RAW_FROM_BENCHMARK_AI",
            ),
            BENCHMARK_V3_METHOD_ID: ("DMS_SOTA_BASELINE",),
        }
    )
)

FROZEN_SOURCE_COMMIT = "49a25effa62fc24f40789c16be6f11bdfb41a4a9"
CHECKPOINT_INTRODUCTION_COMMIT = (
    "e56ce9f196342e9d50edc9fd19c42f72c1fa2047"
)
CHECKPOINT_INTRODUCTION_TIME = "2026-02-24T11:02:20+08:00"
CHECKPOINT_INTRODUCTION_LOCAL_DATE = date(2026, 2, 24)
CAUSAL_ELIGIBILITY_RULE = (
    "TARGET_DRAW_DATE_STRICTLY_AFTER_CHECKPOINT_GIT_INTRODUCTION_LOCAL_DATE"
)
PINNED_DATASET_SHA256 = (
    "2f3d711cb97cddabfc6d351b5a639614da60dc3473cc23368711f605e3fe2d6b"
)
LEDGER_RESOURCE_NAME = (
    "biglotto_ai_checkpoint_wave44_ticket_ledger_v1.json"
)
LEDGER_SCHEMA_VERSION = "BIG_LOTTO_AI_CHECKPOINT_WAVE44_TICKET_LEDGER_V1"
LEDGER_FILE_SHA256 = (
    "4bced583132b8409310454775d3405fdc534f3ecb0f92ccb39723c4fe4b92173"
)
LEDGER_CONTENT_SHA256 = (
    "b159977ad040a110a27d3cf6793100d95b808f19660aff54efcab823e6598072"
)
SOURCE_REFERENCE_RUNTIME = (
    "CPYTHON_3_9_6_TORCH_2_8_0_NUMPY_1_26_2_CPU_MKLDNN_MODEL_EVAL"
)
MODEL_CONTEXT_DRAW_COUNT = 15
MODEL_CANDIDATE_K = 49


class LegacyCheckpointNativeWave44Error(ValueError):
    """The request or packaged ticket ledger violates the wave-44 contract."""


class LegacyCheckpointNativeWave44SourceError(
    LegacyCheckpointNativeWave44Error
):
    """A target cannot safely consume a frozen checkpoint ticket."""

    def __init__(self, reason_code: str) -> None:
        super().__init__(reason_code)
        self.reason_code = reason_code


@dataclass(frozen=True, slots=True)
class LegacyCheckpointNativeWave44Request:
    legacy_method_id: str
    target_draw_number: str
    target_draw_date: date
    history: tuple[LegacyHistoryDraw, ...]
    dataset_sha256: str
    replicate_id: int = 0
    user_seed: str | int = DEFAULT_SOURCE_NATIVE_WAVE44_USER_SEED


@dataclass(frozen=True, slots=True)
class LegacyCheckpointNativeWave44Metadata:
    protocol: str
    legacy_method_id: str
    source_sha256: str
    target_draw_number: str
    target_draw_date: str
    replicate_id: int
    user_seed: str | int
    seed_material: str
    seed_digest: str
    seed_integer: int
    random_protocol: str
    randomness_used: bool
    randomness_reproduction: str
    history_draw_count: int
    history_first_draw_number: str
    history_cutoff_draw_number: str
    source_history_order: str
    source_history_order_detail: str
    model_context_draw_count: int
    model_context_numbers_sha256: str
    source_candidate_k_values: tuple[int, ...]
    candidate_k: None
    native_ticket_count: int
    native_ticket_count_semantics: str
    native_ticket_order: str
    native_duplicate_ticket_count: int
    combination_count: None
    local_source_configuration: str
    imported_comparators_excluded: tuple[str, ...]
    checkpoint_path: str
    checkpoint_sha256: str
    checkpoint_blob_id: str
    checkpoint_introduction_commit: str
    checkpoint_introduction_time: str
    causal_eligibility_rule: str
    source_reference_runtime: str
    ledger_schema_version: str
    ledger_file_sha256: str
    ledger_content_sha256: str
    ledger_target_index: int
    frozen_support_artifacts: tuple[tuple[str, str], ...]

    def canonical_dict(self) -> dict[str, object]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class LegacyCheckpointNativeWave44Result:
    tickets: tuple[Ticket, ...]
    metadata: LegacyCheckpointNativeWave44Metadata


@dataclass(frozen=True, slots=True)
class _Ledger:
    targets: tuple[str, ...]
    context_sha256: tuple[str, ...]
    tickets_by_method: MappingProxyType[str, tuple[Ticket, ...]]


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _ticket(value: object) -> Ticket:
    if not isinstance(value, list):
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 ticket must be an array"
        )
    values = cast(list[object], value)
    integer_values = (
        cast(list[int], values)
        if all(type(number) is int for number in values)
        else []
    )
    if (
        len(values) != 6
        or len(integer_values) != 6
        or len(set(values)) != 6
        or integer_values != sorted(integer_values)
        or any(not 1 <= cast(int, number) <= 49 for number in values)
    ):
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 ticket is not a sorted legal ticket"
        )
    return cast(Ticket, tuple(integer_values))


@lru_cache(maxsize=1)
def _load_ledger() -> _Ledger:
    resource = files("lottolab.strategies.data").joinpath(
        LEDGER_RESOURCE_NAME
    )
    raw = resource.read_bytes()
    if hashlib.sha256(raw).hexdigest() != LEDGER_FILE_SHA256:
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 ledger file SHA changed"
        )
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 ledger is invalid JSON"
        ) from exc
    if not isinstance(parsed, dict):
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 ledger must be an object"
        )
    document = cast(dict[str, Any], parsed)
    claimed_content_sha256 = document.pop("ledger_content_sha256", None)
    if (
        claimed_content_sha256 != LEDGER_CONTENT_SHA256
        or hashlib.sha256(_canonical_bytes(document)).hexdigest()
        != LEDGER_CONTENT_SHA256
        or document.get("ledger_schema_version")
        != LEDGER_SCHEMA_VERSION
        or document.get("frozen_source_commit") != FROZEN_SOURCE_COMMIT
        or document.get("dataset_sha256") != PINNED_DATASET_SHA256
        or document.get("artifact_introduction_commit")
        != CHECKPOINT_INTRODUCTION_COMMIT
        or document.get("artifact_introduction_time")
        != CHECKPOINT_INTRODUCTION_TIME
        or document.get("causal_eligibility_rule")
        != CAUSAL_ELIGIBILITY_RULE
        or document.get("context_draw_count")
        != MODEL_CONTEXT_DRAW_COUNT
    ):
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 ledger identity changed"
        )
    targets_raw = document.get("target_draw_numbers")
    context_raw = document.get("context_numbers_sha256_by_target")
    tickets_raw = document.get("tickets_by_method")
    if (
        not isinstance(targets_raw, list)
        or not isinstance(context_raw, list)
        or not isinstance(tickets_raw, dict)
    ):
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 ledger layout changed"
        )
    targets_values = cast(list[object], targets_raw)
    context_values = cast(list[object], context_raw)
    if (
        len(targets_values) != 48
        or len(context_values) != 48
        or len(set(targets_values)) != 48
        or any(type(item) is not str or not item for item in targets_values)
        or any(
            type(item) is not str
            or len(item) != 64
            or any(character not in "0123456789abcdef" for character in item)
            for item in context_values
        )
    ):
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 target ledger changed"
        )
    typed_tickets = cast(dict[str, object], tickets_raw)
    if set(typed_tickets) != set(SUPPORTED_SOURCE_NATIVE_WAVE44_METHODS):
        raise LegacyCheckpointNativeWave44Error(
            "packaged wave-44 method set changed"
        )
    by_method: dict[str, tuple[Ticket, ...]] = {}
    for method_id in SUPPORTED_SOURCE_NATIVE_WAVE44_METHODS:
        method_tickets_raw = typed_tickets[method_id]
        if not isinstance(method_tickets_raw, list):
            raise LegacyCheckpointNativeWave44Error(
                "packaged wave-44 method tickets changed"
            )
        method_tickets = tuple(
            _ticket(candidate)
            for candidate in cast(list[object], method_tickets_raw)
        )
        if len(method_tickets) != len(targets_values):
            raise LegacyCheckpointNativeWave44Error(
                "packaged wave-44 method ticket count changed"
            )
        by_method[method_id] = method_tickets
    return _Ledger(
        targets=cast(tuple[str, ...], tuple(targets_values)),
        context_sha256=cast(tuple[str, ...], tuple(context_values)),
        tickets_by_method=MappingProxyType(by_method),
    )


def _validate_request(
    request: LegacyCheckpointNativeWave44Request,
) -> None:
    if (
        request.legacy_method_id
        not in SUPPORTED_SOURCE_NATIVE_WAVE44_METHODS
    ):
        raise LegacyCheckpointNativeWave44Error(
            "legacy method is outside the wave-44 batch"
        )
    if (
        type(request.target_draw_number) is not str
        or not request.target_draw_number
        or type(request.target_draw_date) is not date
        or type(request.replicate_id) is not int
        or request.replicate_id < 0
        or type(request.user_seed) not in (str, int)
        or type(request.dataset_sha256) is not str or not request.dataset_sha256
    ):
        raise LegacyCheckpointNativeWave44Error(
            "invalid frozen checkpoint request identity"
        )
    if request.target_draw_date <= CHECKPOINT_INTRODUCTION_LOCAL_DATE:
        raise LegacyCheckpointNativeWave44SourceError(
            "TARGET_NOT_STRICTLY_AFTER_CHECKPOINT_GIT_INTRODUCTION_LOCAL_DATE"
        )
    if len(request.history) < MODEL_CONTEXT_DRAW_COUNT:
        raise LegacyCheckpointNativeWave44SourceError(
            "AVAILABLE_HISTORY_BELOW_FROZEN_MODEL_CONTEXT"
        )
    seen: set[str] = set()
    for draw in request.history:
        if (
            not draw.draw_number
            or draw.draw_number == request.target_draw_number
            or draw.draw_number in seen
        ):
            raise LegacyCheckpointNativeWave44Error(
                "causal history draw identities are invalid"
            )
        _ticket(list(draw.numbers))
        seen.add(draw.draw_number)


def _context_sha256(
    history: tuple[LegacyHistoryDraw, ...],
) -> str:
    context = [
        list(draw.numbers)
        for draw in history[-MODEL_CONTEXT_DRAW_COUNT:]
    ]
    return hashlib.sha256(
        json.dumps(context, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def generate_legacy_checkpoint_native_wave44_portfolio(
    request: LegacyCheckpointNativeWave44Request,
) -> LegacyCheckpointNativeWave44Result:
    """Return the exact frozen-runtime ticket for one causal target."""

    _validate_request(request)
    ledger = _load_ledger()
    try:
        target_index = ledger.targets.index(request.target_draw_number)
    except ValueError as exc:
        raise LegacyCheckpointNativeWave44SourceError(
            "TARGET_OUTSIDE_FROZEN_CHECKPOINT_TICKET_LEDGER"
        ) from exc
    context_sha256 = _context_sha256(request.history)
    if context_sha256 != ledger.context_sha256[target_index]:
        raise LegacyCheckpointNativeWave44SourceError(
            "FROZEN_MODEL_CONTEXT_IDENTITY_MISMATCH"
        )
    seed_material = "|".join(
        (
            SOURCE_NATIVE_WAVE44_PROTOCOL,
            request.legacy_method_id,
            SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE44_METHOD[
                request.legacy_method_id
            ],
            request.target_draw_number,
            str(request.replicate_id),
            str(request.user_seed),
        )
    )
    seed_digest = hashlib.sha256(
        seed_material.encode("utf-8")
    ).hexdigest()
    checkpoint_path, checkpoint_sha256, checkpoint_blob_id = (
        CHECKPOINT_BY_SOURCE_NATIVE_WAVE44_METHOD[
            request.legacy_method_id
        ]
    )
    ticket = ledger.tickets_by_method[request.legacy_method_id][
        target_index
    ]
    return LegacyCheckpointNativeWave44Result(
        tickets=(ticket,),
        metadata=LegacyCheckpointNativeWave44Metadata(
            protocol=SOURCE_NATIVE_WAVE44_PROTOCOL,
            legacy_method_id=request.legacy_method_id,
            source_sha256=(
                SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE44_METHOD[
                    request.legacy_method_id
                ]
            ),
            target_draw_number=request.target_draw_number,
            target_draw_date=request.target_draw_date.isoformat(),
            replicate_id=request.replicate_id,
            user_seed=request.user_seed,
            seed_material=seed_material,
            seed_digest=seed_digest,
            seed_integer=int(seed_digest, 16),
            random_protocol=(
                "NONE_FROZEN_CHECKPOINT_MODEL_EVAL_TOP_LOGIT_SELECTION"
            ),
            randomness_used=False,
            randomness_reproduction=(
                "SOURCE_RUNTIME_LEDGER_EXACT_TICKET_REPLAY"
            ),
            history_draw_count=len(request.history),
            history_first_draw_number=request.history[0].draw_number,
            history_cutoff_draw_number=request.history[-1].draw_number,
            source_history_order="OLDEST_FIRST",
            source_history_order_detail=(
                "DATABASE_NEWEST_FIRST_REVERSED_TO_OLDEST_FIRST_THEN_"
                "STRICT_PREFIX_BEFORE_TARGET_AND_LAST15_MODEL_CONTEXT"
            ),
            model_context_draw_count=MODEL_CONTEXT_DRAW_COUNT,
            model_context_numbers_sha256=context_sha256,
            source_candidate_k_values=(MODEL_CANDIDATE_K,),
            candidate_k=None,
            native_ticket_count=1,
            native_ticket_count_semantics=(
                NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE44_METHOD[
                    request.legacy_method_id
                ]
            ),
            native_ticket_order="SINGLE_LOCAL_SOURCE_CONFIGURATION_TICKET",
            native_duplicate_ticket_count=0,
            combination_count=None,
            local_source_configuration=(
                LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE44_METHOD[
                    request.legacy_method_id
                ]
            ),
            imported_comparators_excluded=(
                IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE44_METHOD[
                    request.legacy_method_id
                ]
            ),
            checkpoint_path=checkpoint_path,
            checkpoint_sha256=checkpoint_sha256,
            checkpoint_blob_id=checkpoint_blob_id,
            checkpoint_introduction_commit=(
                CHECKPOINT_INTRODUCTION_COMMIT
            ),
            checkpoint_introduction_time=CHECKPOINT_INTRODUCTION_TIME,
            causal_eligibility_rule=CAUSAL_ELIGIBILITY_RULE,
            source_reference_runtime=SOURCE_REFERENCE_RUNTIME,
            ledger_schema_version=LEDGER_SCHEMA_VERSION,
            ledger_file_sha256=LEDGER_FILE_SHA256,
            ledger_content_sha256=LEDGER_CONTENT_SHA256,
            ledger_target_index=target_index,
            frozen_support_artifacts=(
                FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE44_METHOD[
                    request.legacy_method_id
                ]
            ),
        ),
    )


__all__ = [
    "BENCHMARK_AI_METHOD_ID",
    "BENCHMARK_AI_ZDP_METHOD_ID",
    "BENCHMARK_V3_METHOD_ID",
    "CAUSAL_ELIGIBILITY_RULE",
    "CHECKPOINT_BY_SOURCE_NATIVE_WAVE44_METHOD",
    "CHECKPOINT_INTRODUCTION_COMMIT",
    "CHECKPOINT_INTRODUCTION_LOCAL_DATE",
    "CHECKPOINT_INTRODUCTION_TIME",
    "DEFAULT_SOURCE_NATIVE_WAVE44_USER_SEED",
    "FROZEN_SUPPORT_ARTIFACTS_BY_SOURCE_NATIVE_WAVE44_METHOD",
    "IMPORTED_COMPARATORS_EXCLUDED_BY_SOURCE_NATIVE_WAVE44_METHOD",
    "LEDGER_CONTENT_SHA256",
    "LEDGER_FILE_SHA256",
    "LEDGER_RESOURCE_NAME",
    "LEDGER_SCHEMA_VERSION",
    "LOCAL_SOURCE_CONFIGURATION_BY_SOURCE_NATIVE_WAVE44_METHOD",
    "MODEL_CANDIDATE_K",
    "MODEL_CONTEXT_DRAW_COUNT",
    "NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE44_METHOD",
    "PINNED_DATASET_SHA256",
    "SOURCE_NATIVE_WAVE44_PROTOCOL",
    "SOURCE_REFERENCE_RUNTIME",
    "SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE44_METHOD",
    "SUPPORTED_SOURCE_NATIVE_WAVE44_METHODS",
    "LegacyCheckpointNativeWave44Error",
    "LegacyCheckpointNativeWave44Metadata",
    "LegacyCheckpointNativeWave44Request",
    "LegacyCheckpointNativeWave44Result",
    "LegacyCheckpointNativeWave44SourceError",
    "generate_legacy_checkpoint_native_wave44_portfolio",
]
