"""Frozen-runtime FFT portfolio reproduction for BIG_LOTTO wave 45.

The production dependency set intentionally remains unchanged. Exact tickets
are read from a checksummed ledger generated by CPython 3.9, NumPy 1.26.2,
and SciPy 1.12.0 executing the frozen source files.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from functools import lru_cache
from importlib.resources import files
from types import MappingProxyType
from typing import Any, Final, cast

from lottolab.application.legacy_history_native_portfolios import (
    LegacyHistoryDraw,
)
from lottolab.application.strategy_preserving_20_ticket import Ticket

SOURCE_NATIVE_WAVE45_PROTOCOL = "legacy_fft_native_wave45/v1"
DEFAULT_SOURCE_NATIVE_WAVE45_USER_SEED = "biglotto-full-universe-fft-native-wave45-v1"
FROZEN_SOURCE_COMMIT = "49a25effa62fc24f40789c16be6f11bdfb41a4a9"
PINNED_DATASET_SHA256 = "2f3d711cb97cddabfc6d351b5a639614da60dc3473cc23368711f605e3fe2d6b"
SOURCE_REFERENCE_RUNTIME = "CPYTHON_3_9_6_NUMPY_1_26_2_SCIPY_1_12_0_FFTPACK_POCKETFFT"
LEDGER_RESOURCE_NAME = "biglotto_fft_wave45_ticket_ledger_v1.json"
LEDGER_SCHEMA_VERSION = "BIG_LOTTO_LEGACY_FFT_NATIVE_WAVE45_TICKET_LEDGER_V1"
LEDGER_FILE_SHA256 = "eba3d384f550808a6934d0b54d37814847accc87e59630dafc0ed155e5dfb5fe"
LEDGER_CONTENT_SHA256 = "c01fa6591c40faf799981b1682fb106a99e045577218d0478ab653e2043c4899"
CONTEXT_DRAW_COUNT = 500
MODEL_CANDIDATE_K = 49

PP3_METHOD_ID = "tools/backtest_big_lotto_3bet.py"
TRIPLE_ORIGINAL_METHOD_ID = "tools/backtest_biglotto_triple_strike_original.py"
FCF_VS_TS3_METHOD_ID = "tools/backtest_fcf_vs_ts3.py"
TRIPLE_ALIAS_METHOD_ID = "tools/verify_biglotto_3bet_comparison.py"
MARKOV_VS_TRIPLE_METHOD_ID = "tools/verify_markov_vs_triple_2bet.py"

SUPPORTED_SOURCE_NATIVE_WAVE45_METHODS = (
    PP3_METHOD_ID,
    TRIPLE_ORIGINAL_METHOD_ID,
    FCF_VS_TS3_METHOD_ID,
    MARKOV_VS_TRIPLE_METHOD_ID,
)
AUDITED_SOURCE_NATIVE_WAVE45_METHODS = (
    *SUPPORTED_SOURCE_NATIVE_WAVE45_METHODS,
    TRIPLE_ALIAS_METHOD_ID,
)
SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE45_METHOD: Final = MappingProxyType(
    {
        PP3_METHOD_ID: ("245f477b3e77422c33472ab7d093c40526d702cdffb0385e3c2f60bc50b691ba"),
        TRIPLE_ORIGINAL_METHOD_ID: (
            "4a8297a758b90b0a8697a889d2c9f1e9321ca2e1a5cac5322eb4e51d943e7977"
        ),
        FCF_VS_TS3_METHOD_ID: ("efc61a5517309025e22b7e37186a6e23b72d3bca572f02f93af9748a238c91e8"),
        TRIPLE_ALIAS_METHOD_ID: (
            "03bb602d9a26fa431efa55ae4005f81556dbf715a3e42ad225a705f347c3c57a"
        ),
        MARKOV_VS_TRIPLE_METHOD_ID: (
            "2094ee4bc361d87b70e49756966284bb1e996af830ae979d1fe598c75210200a"
        ),
    }
)
MINIMUM_HISTORY_BY_SOURCE_NATIVE_WAVE45_METHOD: Final = MappingProxyType(
    {
        PP3_METHOD_ID: 500,
        TRIPLE_ORIGINAL_METHOD_ID: 500,
        FCF_VS_TS3_METHOD_ID: 150,
        TRIPLE_ALIAS_METHOD_ID: 501,
        MARKOV_VS_TRIPLE_METHOD_ID: 501,
    }
)
NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE45_METHOD: Final = MappingProxyType(
    {
        PP3_METHOD_ID: 3,
        TRIPLE_ORIGINAL_METHOD_ID: 3,
        FCF_VS_TS3_METHOD_ID: 6,
        TRIPLE_ALIAS_METHOD_ID: 3,
        MARKOV_VS_TRIPLE_METHOD_ID: 4,
    }
)
SOURCE_COMBINATION_COUNT_BY_SOURCE_NATIVE_WAVE45_METHOD: Final = MappingProxyType(
    {
        PP3_METHOD_ID: None,
        TRIPLE_ORIGINAL_METHOD_ID: None,
        FCF_VS_TS3_METHOD_ID: 2,
        TRIPLE_ALIAS_METHOD_ID: None,
        MARKOV_VS_TRIPLE_METHOD_ID: 2,
    }
)
SOURCE_COMBINATION_MEMBERS_BY_SOURCE_NATIVE_WAVE45_METHOD: Final = MappingProxyType(
    {
        PP3_METHOD_ID: ("PP3_FOURIER_FOURIER_LAG2_COLD",),
        TRIPLE_ORIGINAL_METHOD_ID: ("TRIPLE_STRIKE_FOURIER_COLD_TAIL",),
        FCF_VS_TS3_METHOD_ID: (
            "TS3_FOURIER_COLD_TAIL",
            "FCF_FOURIER_COLD_FREQUENCY_ORTHOGONAL",
        ),
        TRIPLE_ALIAS_METHOD_ID: ("TRIPLE_STRIKE_FOURIER_COLD_TAIL",),
        MARKOV_VS_TRIPLE_METHOD_ID: (
            "MARKOV_TWO_BET",
            "TRIPLE_STRIKE_FOURIER_COLD_TWO_BET",
        ),
    }
)
NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE45_METHOD: Final = MappingProxyType(
    {
        PP3_METHOD_ID: ("THREE_POSITIONAL_TICKETS_FOURIER_RANK_BLOCKS_THEN_LAG2_ECHO_PLUS_COLD"),
        TRIPLE_ORIGINAL_METHOD_ID: ("THREE_POSITIONAL_TICKETS_FOURIER_COLD_THEN_TAIL_BALANCE"),
        FCF_VS_TS3_METHOD_ID: (
            "SIX_POSITIONAL_TICKETS_TS3_POSITIONS_1_TO_3_THEN_FCF_POSITIONS_4_TO_6"
        ),
        TRIPLE_ALIAS_METHOD_ID: ("DUPLICATE_ALIAS_OF_ORIGINAL_TRIPLE_STRIKE_THREE_TICKETS"),
        MARKOV_VS_TRIPLE_METHOD_ID: (
            "FOUR_POSITIONAL_TICKETS_MARKOV_POSITIONS_1_TO_2_THEN_TRIPLE_STRIKE_POSITIONS_3_TO_4"
        ),
    }
)
INTRA_TICKET_ORDER_SEMANTICS_BY_SOURCE_NATIVE_WAVE45_METHOD: Final = MappingProxyType(
    {
        PP3_METHOD_ID: "SOURCE_ALREADY_SORTED_EACH_TICKET",
        TRIPLE_ORIGINAL_METHOD_ID: "SOURCE_ALREADY_SORTED_EACH_TICKET",
        FCF_VS_TS3_METHOD_ID: "SOURCE_ALREADY_SORTED_EACH_TICKET",
        TRIPLE_ALIAS_METHOD_ID: "SOURCE_ALREADY_SORTED_EACH_TICKET",
        MARKOV_VS_TRIPLE_METHOD_ID: (
            "MARKOV_SOURCE_SCORE_ORDER_CANONICALIZED_TO_SORTED_LEGAL_"
            "TICKET_VALUES_WITHOUT_CHANGING_NUMBER_SET_OR_TICKET_POSITION"
        ),
    }
)


class LegacyFftNativeWave45Error(ValueError):
    """The request or packaged source-runtime ledger is invalid."""


class LegacyFftNativeWave45SourceError(LegacyFftNativeWave45Error):
    """A target cannot produce a source-valid wave-45 portfolio."""

    def __init__(self, reason_code: str) -> None:
        super().__init__(reason_code)
        self.reason_code = reason_code


@dataclass(frozen=True, slots=True)
class LegacyFftNativeWave45Request:
    legacy_method_id: str
    target_draw_number: str
    history: tuple[LegacyHistoryDraw, ...]
    dataset_sha256: str
    replicate_id: int = 0
    user_seed: str | int = DEFAULT_SOURCE_NATIVE_WAVE45_USER_SEED


@dataclass(frozen=True, slots=True)
class LegacyFftNativeWave45Metadata:
    protocol: str
    legacy_method_id: str
    source_sha256: str
    target_draw_number: str
    replicate_id: int
    user_seed: str | int
    seed_material: str
    seed_digest: str
    seed_integer: int
    random_protocol: str
    randomness_used: bool
    randomness_reproduction: str
    history_draw_count: int
    history_first_draw_number: str
    history_cutoff_draw_number: str
    source_history_order: str
    source_history_order_detail: str
    source_minimum_history_draws: int
    context_draw_count: int
    context_numbers_sha256: str
    candidate_k: None
    source_candidate_k_values: tuple[int, ...]
    native_ticket_count: int
    native_ticket_count_semantics: str
    native_ticket_order: str
    native_duplicate_ticket_count: int
    combination_count: None
    source_method_combination_count: int | None
    combination_members: tuple[str, ...]
    intra_ticket_order_semantics: str
    source_reference_runtime: str
    ledger_schema_version: str
    ledger_file_sha256: str
    ledger_content_sha256: str
    ledger_target_index: int

    def canonical_dict(self) -> dict[str, object]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class LegacyFftNativeWave45Result:
    tickets: tuple[Ticket, ...]
    metadata: LegacyFftNativeWave45Metadata


@dataclass(frozen=True, slots=True)
class _Ledger:
    targets: tuple[str, ...]
    context_sha256: tuple[str, ...]
    tickets_by_method: MappingProxyType[str, tuple[tuple[Ticket, ...] | None, ...]]


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _ticket(value: object) -> Ticket:
    if not isinstance(value, list):
        raise LegacyFftNativeWave45Error("packaged wave-45 ticket must be an array")
    values = cast(list[object], value)
    integer_values = (
        cast(list[int], values) if all(type(number) is int for number in values) else []
    )
    if (
        len(values) != 6
        or len(integer_values) != 6
        or integer_values != sorted(integer_values)
        or len(set(values)) != 6
        or any(not 1 <= cast(int, number) <= 49 for number in values)
    ):
        raise LegacyFftNativeWave45Error("packaged wave-45 ticket is not a sorted legal ticket")
    return cast(Ticket, tuple(integer_values))


@lru_cache(maxsize=1)
def _load_ledger() -> _Ledger:
    resource = files("lottolab.strategies.data").joinpath(LEDGER_RESOURCE_NAME)
    raw = resource.read_bytes()
    if hashlib.sha256(raw).hexdigest() != LEDGER_FILE_SHA256:
        raise LegacyFftNativeWave45Error("packaged wave-45 ledger file SHA changed")
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise LegacyFftNativeWave45Error("packaged wave-45 ledger is invalid JSON") from exc
    if not isinstance(parsed, dict):
        raise LegacyFftNativeWave45Error("packaged wave-45 ledger must be an object")
    document = cast(dict[str, Any], parsed)
    claimed_content_sha256 = document.pop("ledger_content_sha256", None)
    if (
        claimed_content_sha256 != LEDGER_CONTENT_SHA256
        or hashlib.sha256(_canonical_bytes(document)).hexdigest() != LEDGER_CONTENT_SHA256
        or document.get("ledger_schema_version") != LEDGER_SCHEMA_VERSION
        or document.get("frozen_source_commit") != FROZEN_SOURCE_COMMIT
        or document.get("dataset_sha256") != PINNED_DATASET_SHA256
        or document.get("source_reference_runtime") != SOURCE_REFERENCE_RUNTIME
        or document.get("context_draw_count") != CONTEXT_DRAW_COUNT
        or document.get("minimum_history_by_method")
        != dict(MINIMUM_HISTORY_BY_SOURCE_NATIVE_WAVE45_METHOD)
        or document.get("source_sha256_by_method")
        != dict(SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE45_METHOD)
    ):
        raise LegacyFftNativeWave45Error("packaged wave-45 ledger identity changed")
    targets_raw = document.get("target_draw_numbers")
    contexts_raw = document.get("context_numbers_sha256_by_target")
    tickets_raw = document.get("tickets_by_method")
    if (
        not isinstance(targets_raw, list)
        or not isinstance(contexts_raw, list)
        or not isinstance(tickets_raw, dict)
    ):
        raise LegacyFftNativeWave45Error("packaged wave-45 ledger layout changed")
    targets = cast(list[object], targets_raw)
    contexts = cast(list[object], contexts_raw)
    if (
        len(targets) != 1999
        or len(contexts) != 1999
        or len(set(targets)) != 1999
        or any(type(item) is not str or not item for item in targets)
        or any(
            type(item) is not str
            or len(item) != 64
            or any(character not in "0123456789abcdef" for character in item)
            for item in contexts
        )
    ):
        raise LegacyFftNativeWave45Error("packaged wave-45 target sequence changed")
    by_method: dict[str, tuple[tuple[Ticket, ...] | None, ...]] = {}
    typed_tickets = cast(dict[str, object], tickets_raw)
    if set(typed_tickets) != set(AUDITED_SOURCE_NATIVE_WAVE45_METHODS):
        raise LegacyFftNativeWave45Error("packaged wave-45 method set changed")
    for method_id in AUDITED_SOURCE_NATIVE_WAVE45_METHODS:
        raw_sequence = typed_tickets[method_id]
        if not isinstance(raw_sequence, list):
            raise LegacyFftNativeWave45Error("packaged wave-45 method sequence changed")
        sequence: list[tuple[Ticket, ...] | None] = []
        for candidate in cast(list[object], raw_sequence):
            if candidate is None:
                sequence.append(None)
                continue
            if not isinstance(candidate, list):
                raise LegacyFftNativeWave45Error("packaged wave-45 portfolio changed")
            portfolio = tuple(_ticket(ticket) for ticket in cast(list[object], candidate))
            if len(portfolio) != NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE45_METHOD[method_id]:
                raise LegacyFftNativeWave45Error("packaged wave-45 native ticket count changed")
            sequence.append(portfolio)
        if len(sequence) != len(targets):
            raise LegacyFftNativeWave45Error("packaged wave-45 target alignment changed")
        by_method[method_id] = tuple(sequence)
    return _Ledger(
        targets=cast(tuple[str, ...], tuple(targets)),
        context_sha256=cast(tuple[str, ...], tuple(contexts)),
        tickets_by_method=MappingProxyType(by_method),
    )


def load_legacy_fft_native_wave45_ledger_for_verification() -> _Ledger:
    """Expose the immutable checksummed ledger to contract tests."""

    return _load_ledger()


def _validate_request(request: LegacyFftNativeWave45Request) -> None:
    if request.legacy_method_id not in SUPPORTED_SOURCE_NATIVE_WAVE45_METHODS:
        raise LegacyFftNativeWave45Error("legacy method is outside the executable wave-45 batch")
    if (
        type(request.target_draw_number) is not str
        or not request.target_draw_number
        or request.dataset_sha256 != PINNED_DATASET_SHA256
        or type(request.replicate_id) is not int
        or request.replicate_id < 0
        or type(request.user_seed) not in (str, int)
    ):
        raise LegacyFftNativeWave45Error("invalid frozen FFT request identity")
    minimum = MINIMUM_HISTORY_BY_SOURCE_NATIVE_WAVE45_METHOD[request.legacy_method_id]
    if len(request.history) < minimum:
        raise LegacyFftNativeWave45SourceError("AVAILABLE_HISTORY_BELOW_FROZEN_SOURCE_MINIMUM")
    seen: set[str] = set()
    for draw in request.history:
        if (
            not draw.draw_number
            or draw.draw_number == request.target_draw_number
            or draw.draw_number in seen
        ):
            raise LegacyFftNativeWave45Error("causal history draw identities are invalid")
        _ticket(list(draw.numbers))
        seen.add(draw.draw_number)


def _context_sha256(history: tuple[LegacyHistoryDraw, ...]) -> str:
    context = [list(draw.numbers) for draw in history[-CONTEXT_DRAW_COUNT:]]
    return hashlib.sha256(json.dumps(context, separators=(",", ":")).encode("utf-8")).hexdigest()


def generate_legacy_fft_native_wave45_portfolio(
    request: LegacyFftNativeWave45Request,
) -> LegacyFftNativeWave45Result:
    """Return the exact positional portfolio for one causal target."""

    _validate_request(request)
    ledger = _load_ledger()
    try:
        target_index = ledger.targets.index(request.target_draw_number)
    except ValueError as exc:
        raise LegacyFftNativeWave45SourceError("TARGET_OUTSIDE_FROZEN_FFT_TICKET_LEDGER") from exc
    context_sha256 = _context_sha256(request.history)
    if context_sha256 != ledger.context_sha256[target_index]:
        raise LegacyFftNativeWave45SourceError("FROZEN_SOURCE_CONTEXT_IDENTITY_MISMATCH")
    tickets = ledger.tickets_by_method[request.legacy_method_id][target_index]
    if tickets is None:
        raise LegacyFftNativeWave45SourceError("AVAILABLE_HISTORY_BELOW_FROZEN_SOURCE_MINIMUM")
    seed_material = "|".join(
        (
            SOURCE_NATIVE_WAVE45_PROTOCOL,
            request.legacy_method_id,
            SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE45_METHOD[request.legacy_method_id],
            request.target_draw_number,
            str(request.replicate_id),
            str(request.user_seed),
        )
    )
    seed_digest = hashlib.sha256(seed_material.encode("utf-8")).hexdigest()
    method_id = request.legacy_method_id
    return LegacyFftNativeWave45Result(
        tickets=tickets,
        metadata=LegacyFftNativeWave45Metadata(
            protocol=SOURCE_NATIVE_WAVE45_PROTOCOL,
            legacy_method_id=method_id,
            source_sha256=(SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE45_METHOD[method_id]),
            target_draw_number=request.target_draw_number,
            replicate_id=request.replicate_id,
            user_seed=request.user_seed,
            seed_material=seed_material,
            seed_digest=seed_digest,
            seed_integer=int(seed_digest, 16),
            random_protocol="NONE_DETERMINISTIC_FROZEN_SOURCE",
            randomness_used=False,
            randomness_reproduction="NOT_APPLICABLE",
            history_draw_count=len(request.history),
            history_first_draw_number=request.history[0].draw_number,
            history_cutoff_draw_number=request.history[-1].draw_number,
            source_history_order="OLDEST_FIRST",
            source_history_order_detail=(
                "DATABASE_NEWEST_FIRST_REVERSED_ONCE_THEN_STRICT_PREFIX_"
                "BEFORE_TARGET_WITH_TRAILING_500_MAXIMUM_SOURCE_CONTEXT"
            ),
            source_minimum_history_draws=(
                MINIMUM_HISTORY_BY_SOURCE_NATIVE_WAVE45_METHOD[method_id]
            ),
            context_draw_count=min(
                len(request.history),
                CONTEXT_DRAW_COUNT,
            ),
            context_numbers_sha256=context_sha256,
            candidate_k=None,
            source_candidate_k_values=(MODEL_CANDIDATE_K,),
            native_ticket_count=len(tickets),
            native_ticket_count_semantics=(
                NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE45_METHOD[method_id]
            ),
            native_ticket_order=("FROZEN_SOURCE_CONFIGURATION_THEN_POSITIONAL_BET_ORDER"),
            native_duplicate_ticket_count=len(tickets) - len(set(tickets)),
            combination_count=None,
            source_method_combination_count=(
                SOURCE_COMBINATION_COUNT_BY_SOURCE_NATIVE_WAVE45_METHOD[method_id]
            ),
            combination_members=(
                SOURCE_COMBINATION_MEMBERS_BY_SOURCE_NATIVE_WAVE45_METHOD[method_id]
            ),
            intra_ticket_order_semantics=(
                INTRA_TICKET_ORDER_SEMANTICS_BY_SOURCE_NATIVE_WAVE45_METHOD[method_id]
            ),
            source_reference_runtime=SOURCE_REFERENCE_RUNTIME,
            ledger_schema_version=LEDGER_SCHEMA_VERSION,
            ledger_file_sha256=LEDGER_FILE_SHA256,
            ledger_content_sha256=LEDGER_CONTENT_SHA256,
            ledger_target_index=target_index,
        ),
    )


__all__ = [
    "AUDITED_SOURCE_NATIVE_WAVE45_METHODS",
    "CONTEXT_DRAW_COUNT",
    "DEFAULT_SOURCE_NATIVE_WAVE45_USER_SEED",
    "FCF_VS_TS3_METHOD_ID",
    "FROZEN_SOURCE_COMMIT",
    "INTRA_TICKET_ORDER_SEMANTICS_BY_SOURCE_NATIVE_WAVE45_METHOD",
    "LEDGER_CONTENT_SHA256",
    "LEDGER_FILE_SHA256",
    "LEDGER_RESOURCE_NAME",
    "LEDGER_SCHEMA_VERSION",
    "MARKOV_VS_TRIPLE_METHOD_ID",
    "MINIMUM_HISTORY_BY_SOURCE_NATIVE_WAVE45_METHOD",
    "MODEL_CANDIDATE_K",
    "NATIVE_TICKET_COUNT_BY_SOURCE_NATIVE_WAVE45_METHOD",
    "NATIVE_TICKET_SEMANTICS_BY_SOURCE_NATIVE_WAVE45_METHOD",
    "PINNED_DATASET_SHA256",
    "PP3_METHOD_ID",
    "SOURCE_COMBINATION_COUNT_BY_SOURCE_NATIVE_WAVE45_METHOD",
    "SOURCE_COMBINATION_MEMBERS_BY_SOURCE_NATIVE_WAVE45_METHOD",
    "SOURCE_NATIVE_WAVE45_PROTOCOL",
    "SOURCE_REFERENCE_RUNTIME",
    "SOURCE_SHA256_BY_SOURCE_NATIVE_WAVE45_METHOD",
    "SUPPORTED_SOURCE_NATIVE_WAVE45_METHODS",
    "TRIPLE_ALIAS_METHOD_ID",
    "TRIPLE_ORIGINAL_METHOD_ID",
    "LegacyFftNativeWave45Error",
    "LegacyFftNativeWave45Metadata",
    "LegacyFftNativeWave45Request",
    "LegacyFftNativeWave45Result",
    "LegacyFftNativeWave45SourceError",
    "generate_legacy_fft_native_wave45_portfolio",
    "load_legacy_fft_native_wave45_ledger_for_verification",
]
