"""A bounded, reproducible, seeded local search targeting exact coverage.

This is `STRATEGY_MATRIX_PHASE5_DIVERSIFICATION_CONSTRUCTOR_FRONTIER_DESIGN_R1`
arm C (`BOUNDED_COVERAGE_OPTIMIZER`). See
`docs/research/strategy-matrix-phase5-diversification-constructor-frontier-design-r1.md`
for the frozen search-space/objective/budget contract this module
implements exactly. Unlike `greedy_min_overlap_constructor` (arm B, which
targets low overlap as a cheap proxy and is exhaustive per step), this
module targets the real objective -- exact `>= minimum_matches` winning-
space coverage, evaluated by complete enumeration -- and is explicitly
budget-capped rather than exhaustive, because a full-enumeration
coverage evaluation is expensive per candidate. It is never invoked at
real B649 scale (`pool_size=49, draw_size=6`) by this design task -- only
toy/synthetic sizes, per that document's scope boundary. No output of this
module is a retained "final" B649 challenger portfolio.

Search family: multi-restart randomized greedy construction, followed by
bounded local search that swaps one ticket at a time for a same-sample
steepest-ascent replacement. Each restart is independently seeded and
fully deterministic given `seed`; there is no dependence on wall-clock
time, hash randomization, or any other non-reproducible source.
"""

from __future__ import annotations

import itertools
import math
import random
from dataclasses import dataclass
from fractions import Fraction


def _ticket_bitmask(ticket: tuple[int, ...]) -> int:
    mask = 0
    for number in ticket:
        mask |= 1 << (number - 1)
    return mask


def exact_portfolio_coverage(
    pool_size: int,
    draw_size: int,
    minimum_matches: int,
    portfolio: tuple[tuple[int, ...], ...],
) -> Fraction:
    """Exact `P(>= 1 ticket in portfolio has >= minimum_matches matches)`.

    Complete enumeration over all `C(pool_size, draw_size)` possible draws
    -- the same method `tools/run_diversification_coverage_p638_zone1_v1.py`
    uses for a single fixed portfolio, generalized here to be called
    repeatedly against arbitrary candidate portfolios during search. This
    is why this search family is budget-capped rather than exhaustive: at
    real B649 scale (`C(49,6) = 13,983,816`), each call to this function
    re-enumerates the full winning space.
    """

    total_draws = math.comb(pool_size, draw_size)
    ticket_masks = [_ticket_bitmask(ticket) for ticket in portfolio]
    qualifying_draws = 0
    for draw in itertools.combinations(range(1, pool_size + 1), draw_size):
        draw_mask = _ticket_bitmask(draw)
        if any((draw_mask & mask).bit_count() >= minimum_matches for mask in ticket_masks):
            qualifying_draws += 1
    return Fraction(qualifying_draws, total_draws)


def _sample_distinct_candidates(
    rng: random.Random,
    pool_size: int,
    draw_size: int,
    sample_size: int,
    exclude: set[tuple[int, ...]],
    max_attempts: int,
) -> list[tuple[int, ...]]:
    """Up to `sample_size` distinct `draw_size`-subsets not in `exclude`.

    Draws are generated by `rng.sample(range(1, pool_size + 1), draw_size)`
    (the pool's own PRNG order), sorted into canonical ascending tuples,
    and de-duplicated against both `exclude` and each other. Bounded by
    `max_attempts` draws so a near-exhausted candidate space cannot loop
    forever; returns fewer than `sample_size` candidates in that case
    rather than raising, which is disclosed as part of this procedure, not
    a silent failure.
    """

    found: list[tuple[int, ...]] = []
    seen = set(exclude)
    attempts = 0
    while len(found) < sample_size and attempts < max_attempts:
        attempts += 1
        candidate = tuple(sorted(rng.sample(range(1, pool_size + 1), draw_size)))
        if candidate in seen:
            continue
        seen.add(candidate)
        found.append(candidate)
    return found


@dataclass(frozen=True)
class RestartOutcome:
    portfolio: tuple[tuple[int, ...], ...]
    coverage: Fraction
    evaluations_used: int
    converged: bool
    swap_passes_run: int


@dataclass(frozen=True)
class BoundedSearchResult:
    portfolio: tuple[tuple[int, ...], ...]
    coverage: Fraction
    evaluations_used: int
    restart_outcomes: tuple[RestartOutcome, ...]
    best_restart_index: int


def _build_by_randomized_greedy(
    rng: random.Random,
    pool_size: int,
    draw_size: int,
    minimum_matches: int,
    ticket_count: int,
    candidate_sample_size: int,
    max_sample_attempts: int,
) -> tuple[tuple[tuple[int, ...], ...], int]:
    portfolio: list[tuple[int, ...]] = []
    evaluations = 0
    for _ in range(ticket_count):
        candidates = _sample_distinct_candidates(
            rng, pool_size, draw_size, candidate_sample_size, set(portfolio), max_sample_attempts
        )
        best_candidate: tuple[int, ...] | None = None
        best_coverage: Fraction | None = None
        for candidate in candidates:
            trial = (*portfolio, candidate)
            coverage = exact_portfolio_coverage(pool_size, draw_size, minimum_matches, trial)
            evaluations += 1
            is_new_best = best_coverage is None or coverage > best_coverage
            is_lexicographic_tie_winner = (
                best_candidate is not None
                and coverage == best_coverage
                and candidate < best_candidate
            )
            if is_new_best or is_lexicographic_tie_winner:
                best_coverage = coverage
                best_candidate = candidate
        assert best_candidate is not None  # candidate_sample_size >= 1 and space not exhausted
        portfolio.append(best_candidate)
    return tuple(portfolio), evaluations


def _local_swap_search(
    rng: random.Random,
    pool_size: int,
    draw_size: int,
    minimum_matches: int,
    portfolio: tuple[tuple[int, ...], ...],
    candidate_sample_size: int,
    max_swap_passes: int,
    max_sample_attempts: int,
    evaluations_so_far: int,
) -> tuple[tuple[tuple[int, ...], ...], Fraction, int, bool, int]:
    current = list(portfolio)
    evaluations = evaluations_so_far
    current_coverage = exact_portfolio_coverage(
        pool_size, draw_size, minimum_matches, tuple(current)
    )
    evaluations += 1
    passes_run = 0
    converged = False
    for pass_index in range(max_swap_passes):
        passes_run = pass_index + 1
        improved_this_pass = False
        for slot in range(len(current)):
            exclude = set(current) - {current[slot]}
            candidates = _sample_distinct_candidates(
                rng, pool_size, draw_size, candidate_sample_size, exclude, max_sample_attempts
            )
            best_candidate = current[slot]
            best_coverage = current_coverage
            for candidate in candidates:
                if candidate == current[slot]:
                    continue
                trial = [*current[:slot], candidate, *current[slot + 1 :]]
                coverage = exact_portfolio_coverage(
                    pool_size, draw_size, minimum_matches, tuple(trial)
                )
                evaluations += 1
                if coverage > best_coverage or (
                    coverage == best_coverage and candidate < best_candidate
                ):
                    best_coverage = coverage
                    best_candidate = candidate
            if best_coverage > current_coverage:
                current[slot] = best_candidate
                current_coverage = best_coverage
                improved_this_pass = True
        if not improved_this_pass:
            converged = True
            break
    return tuple(current), current_coverage, evaluations, converged, passes_run


def restart_greedy_swap_search(
    pool_size: int,
    draw_size: int,
    minimum_matches: int,
    ticket_count: int,
    *,
    seed: int,
    restart_count: int,
    candidate_sample_size: int,
    max_swap_passes: int,
    max_sample_attempts: int = 200,
) -> BoundedSearchResult:
    """The frozen `BOUNDED_COVERAGE_OPTIMIZER` search family, one call per `k`.

    Independent-per-`k` by design: call this once per exposure-ladder
    rung with that rung's own `ticket_count`; there is no carry-over
    portfolio between calls and no nested-prefix guarantee across `k`
    (unlike arm A/B). Each of `restart_count` restarts uses its own
    `random.Random(seed + restart_index)`, so the whole search is fully
    reproducible given `seed`. Restart `r` runs randomized-greedy
    construction (`candidate_sample_size` sampled candidates per ticket,
    best-of-sample by exact coverage, ties broken by the lexicographically
    smaller candidate) followed by up to `max_swap_passes` full sweeps of
    same-sample steepest-ascent single-ticket swaps, stopping a restart
    early the first time a full sweep makes no improving swap. The best
    restart (by final coverage, ties broken by the lexicographically
    smaller portfolio) is returned. `evaluations_used` bounds the exact
    number of `exact_portfolio_coverage` calls actually performed, always
    at most `restart_count * (ticket_count * candidate_sample_size +
    max_swap_passes * ticket_count * (candidate_sample_size + 1))`.
    """

    if restart_count < 1:
        raise ValueError("restart_count must be >= 1")

    restart_outcomes: list[RestartOutcome] = []
    for restart_index in range(restart_count):
        rng = random.Random(seed + restart_index)
        built_portfolio, build_evaluations = _build_by_randomized_greedy(
            rng,
            pool_size,
            draw_size,
            minimum_matches,
            ticket_count,
            candidate_sample_size,
            max_sample_attempts,
        )
        final_portfolio, final_coverage, total_evaluations, converged, passes_run = (
            _local_swap_search(
                rng,
                pool_size,
                draw_size,
                minimum_matches,
                built_portfolio,
                candidate_sample_size,
                max_swap_passes,
                max_sample_attempts,
                build_evaluations,
            )
        )
        restart_outcomes.append(
            RestartOutcome(
                portfolio=final_portfolio,
                coverage=final_coverage,
                evaluations_used=total_evaluations,
                converged=converged,
                swap_passes_run=passes_run,
            )
        )

    best_index = 0
    for index, outcome in enumerate(restart_outcomes[1:], start=1):
        current_best = restart_outcomes[best_index]
        if outcome.coverage > current_best.coverage or (
            outcome.coverage == current_best.coverage
            and outcome.portfolio < current_best.portfolio
        ):
            best_index = index

    best = restart_outcomes[best_index]
    total_evaluations = sum(outcome.evaluations_used for outcome in restart_outcomes)
    return BoundedSearchResult(
        portfolio=best.portfolio,
        coverage=best.coverage,
        evaluations_used=total_evaluations,
        restart_outcomes=tuple(restart_outcomes),
        best_restart_index=best_index,
    )
