"""Executable old/new parity for the legacy frontend Zone Balance donor."""

from __future__ import annotations

import sqlite3

import pytest

from lottolab.application.use_cases.generate_bet import (
    GenerateOneBetInput,
    GenerateOneBetStatus,
    GeneratePortfolioReason,
    GeneratePortfolioStatus,
    build_production_generate_one_bet,
    build_production_generate_portfolio,
)
from lottolab.domain.draws import LotteryType
from lottolab.domain.strategies import LifecycleStatus, ResponseShape
from lottolab.strategies.adapters import BigLottoFrontendZoneBalanceAdapter
from lottolab.strategies.adapters.base import (
    CausalDrawRow,
    InsufficientHistory,
    InvalidOutput,
    UnsupportedLotteryType,
)
from lottolab.strategies.catalog import production_catalog
from lottolab.strategies.executable_registry import ExecutableRegistry

STRATEGY_ID = "legacy_biglotto__frontend_zone_balance_strategy__6a016aa83b3e"


def _stride_row(index: int) -> CausalDrawRow:
    numbers = tuple(sorted(((index + step * 8) % 49) + 1 for step in range(6)))
    return CausalDrawRow(
        draw=f"frontend-zone-balance-{index}",
        date=f"2020-{(index % 12) + 1:02d}-{(index % 28) + 1:02d}",
        numbers=numbers,
    )


def _history(length: int) -> tuple[CausalDrawRow, ...]:
    """LottoLab's canonical oldest-first causal history."""
    return tuple(_stride_row(index) for index in range(length))


# Captured from the revived donor class with its actual algorithm and a
# synchronous StatisticsService-compatible stub, not generated by the target.
DONOR_GOLDENS: dict[int, tuple[int, ...]] = {
    1: (1, 2, 3, 4, 5, 9),
    2: (1, 2, 3, 4, 9, 10),
    10: (1, 2, 3, 4, 9, 10),
    50: (1, 2, 3, 4, 5, 9),
    500: (1, 2, 3, 4, 9, 10),
}


@pytest.mark.parametrize("length", sorted(DONOR_GOLDENS))
def test_matches_executed_donor_golden(length: int) -> None:
    assert BigLottoFrontendZoneBalanceAdapter().get_one_bet(
        _history(length), LotteryType.BIG_LOTTO
    ) == (DONOR_GOLDENS[length], None)


def test_zone_tie_prefers_earliest_declared_zone_and_number_ties_are_ascending() -> None:
    tie_history = (
        CausalDrawRow("tie-0", "tie-0", (1, 2, 3, 4, 5, 6)),
        CausalDrawRow("tie-1", "tie-1", (11, 12, 13, 14, 15, 16)),
    )
    assert BigLottoFrontendZoneBalanceAdapter().get_one_bet(
        tie_history, LotteryType.BIG_LOTTO
    ) == ((1, 2, 3, 4, 5, 6), None)

    later_zone_history = (
        CausalDrawRow("late-0", "late-0", (41, 42, 43, 44, 45, 46)),
        CausalDrawRow("late-1", "late-1", (41, 42, 43, 44, 45, 46)),
    )
    assert BigLottoFrontendZoneBalanceAdapter().get_one_bet(
        later_zone_history, LotteryType.BIG_LOTTO
    ) == ((41, 42, 43, 44, 45, 46), None)


def test_frequency_aggregation_is_invariant_to_causal_row_order() -> None:
    adapter = BigLottoFrontendZoneBalanceAdapter()
    history = _history(20)
    assert adapter.get_one_bet(history, LotteryType.BIG_LOTTO) == adapter.get_one_bet(
        tuple(reversed(history)), LotteryType.BIG_LOTTO
    )


def test_minimum_history_and_determinism_are_explicit() -> None:
    adapter = BigLottoFrontendZoneBalanceAdapter()
    with pytest.raises(InsufficientHistory):
        adapter.get_one_bet((), LotteryType.BIG_LOTTO)

    first = adapter.get_one_bet_with_emission(_history(500), LotteryType.BIG_LOTTO)
    second = adapter.get_one_bet_with_emission(_history(500), LotteryType.BIG_LOTTO)
    assert first == second
    assert first.emitted_main_numbers == DONOR_GOLDENS[500]
    assert first.legal_main_numbers == DONOR_GOLDENS[500]
    assert first.special_number is None


def test_invalid_history_and_wrong_lottery_fail_closed() -> None:
    adapter = BigLottoFrontendZoneBalanceAdapter()
    invalid = (CausalDrawRow("bad", "bad", (1, 1, 2, 3, 4, 5)),)
    with pytest.raises(InvalidOutput):
        adapter.get_one_bet(invalid, LotteryType.BIG_LOTTO)
    with pytest.raises(UnsupportedLotteryType):
        adapter.get_one_bet(_history(1), LotteryType.DAILY_539)


def test_catalog_and_registry_add_exactly_one_online_identity() -> None:
    catalog = production_catalog()
    descriptor = catalog.get(STRATEGY_ID)
    assert len(catalog) == 123
    assert [item.strategy_id for item in catalog].count(STRATEGY_ID) == 1
    assert descriptor.strategy_id == BigLottoFrontendZoneBalanceAdapter.strategy_id
    assert descriptor.strategy_name == BigLottoFrontendZoneBalanceAdapter.strategy_name
    assert descriptor.version == BigLottoFrontendZoneBalanceAdapter.strategy_version
    assert descriptor.lottery_types == (LotteryType.BIG_LOTTO,)
    assert descriptor.lifecycle_status is LifecycleStatus.ONLINE
    assert descriptor.executable is True
    assert descriptor.response_shape is ResponseShape.SINGLE_TICKET
    assert descriptor.native_ticket_count == 1
    assert descriptor.min_history == 1
    assert descriptor.adapter_path == (
        "lottolab.strategies.adapters.biglotto_frontend_zone_balance:"
        "BigLottoFrontendZoneBalanceAdapter"
    )
    assert (
        "legacy_source_sha256:"
        "6a016aa83b3ebcaed1776fa6d8b10009c5944a4969a4dd2c3dbad8bbcb9aeda2"
        in descriptor.provenance
    )
    assert "legacy_symbol:ZoneBalanceStrategy.predict" in descriptor.provenance
    assert "legacy_runtime:PredictionEngine.strategies.zone_balance" in descriptor.provenance
    assert (
        "donor_execution:REVIVED_WITH_SYNCHRONOUS_STATISTICS_SERVICE_STUB_ISOLATED"
        in descriptor.provenance
    )
    assert ExecutableRegistry(catalog).load_adapter(STRATEGY_ID) is (
        BigLottoFrontendZoneBalanceAdapter
    )


def _request(history: tuple[CausalDrawRow, ...]) -> GenerateOneBetInput:
    return GenerateOneBetInput(
        strategy_id=STRATEGY_ID,
        lottery_type=LotteryType.BIG_LOTTO,
        history=history,
    )


def test_production_single_ticket_generation_path_is_reachable() -> None:
    result = build_production_generate_one_bet().execute(_request(_history(20)))
    assert result.status is GenerateOneBetStatus.OK
    assert result.numbers == DONOR_GOLDENS[10]
    assert result.special_number is None
    assert result.reason_code is None


def test_portfolio_path_rejects_single_ticket_identity() -> None:
    result = build_production_generate_portfolio().execute(_request(_history(20)))
    assert result.status is GeneratePortfolioStatus.WRONG_RESPONSE_PATH
    assert result.numbers is None
    assert result.reason_code is GeneratePortfolioReason.STRATEGY_IS_NOT_PORTFOLIO


def test_production_generation_never_opens_a_database(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def _forbidden_connect(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("Frontend Zone Balance Strategy must not open a database")

    monkeypatch.setattr(sqlite3, "connect", _forbidden_connect)
    result = build_production_generate_one_bet().execute(_request(_history(20)))
    assert result.status is GenerateOneBetStatus.OK
    assert result.numbers == DONOR_GOLDENS[10]
