"""Executable old/new parity for the legacy frontend Sum-range donor."""

from __future__ import annotations

import sqlite3

import pytest

from lottolab.application.use_cases.generate_bet import (
    GenerateOneBetInput,
    GenerateOneBetStatus,
    GeneratePortfolioReason,
    GeneratePortfolioStatus,
    build_production_generate_one_bet,
    build_production_generate_portfolio,
)
from lottolab.domain.draws import LotteryType
from lottolab.domain.strategies import LifecycleStatus, ResponseShape
from lottolab.strategies.adapters import BigLottoFrontendSumRangeAdapter
from lottolab.strategies.adapters.base import (
    CausalDrawRow,
    InsufficientHistory,
    InvalidOutput,
    UnsupportedLotteryType,
)
from lottolab.strategies.catalog import production_catalog
from lottolab.strategies.executable_registry import ExecutableRegistry

STRATEGY_ID = "legacy_biglotto__frontend_sum_range_strategy__4941213e6c46"


def _stride_row(index: int) -> CausalDrawRow:
    numbers = tuple(sorted(((index + step * 8) % 49) + 1 for step in range(6)))
    return CausalDrawRow(
        draw=f"frontend-sum-range-{index}",
        date=f"2020-{(index % 12) + 1:02d}-{(index % 28) + 1:02d}",
        numbers=numbers,
    )


def _history(length: int) -> tuple[CausalDrawRow, ...]:
    """LottoLab's canonical oldest-first causal history."""
    return tuple(_stride_row(index) for index in range(length))


# Captured from the revived donor class with its actual algorithm and a
# synchronous StatisticsService-compatible stub, not generated by the target.
DONOR_GOLDENS: dict[int, tuple[int, ...]] = {
    1: (1, 9, 17, 25, 33, 41),
    2: (1, 2, 9, 10, 17, 18),
    3: (1, 2, 3, 9, 10, 11),
    6: (1, 2, 3, 4, 5, 6),
    9: (1, 9, 17, 25, 33, 41),
    10: (1, 9, 10, 17, 18, 25),
    11: (1, 2, 9, 10, 11, 17),
    20: (1, 2, 3, 41, 42, 44),
    50: (1, 9, 17, 25, 33, 41),
    100: (1, 2, 9, 10, 17, 18),
    300: (1, 2, 3, 4, 5, 6),
    500: (1, 9, 10, 17, 18, 25),
    750: (1, 2, 3, 4, 5, 6),
}


FALLBACK_HISTORY = (
    CausalDrawRow("fallback-0", "fallback-0", (18, 29, 30, 42, 43, 48)),
    CausalDrawRow("fallback-1", "fallback-1", (6, 7, 10, 23, 26, 35)),
    CausalDrawRow("fallback-2", "fallback-2", (4, 33, 34, 35, 42, 48)),
    CausalDrawRow("fallback-3", "fallback-3", (18, 24, 29, 31, 33, 48)),
    CausalDrawRow("fallback-4", "fallback-4", (21, 24, 29, 33, 39, 46)),
    CausalDrawRow("fallback-5", "fallback-5", (7, 20, 23, 25, 26, 32)),
    CausalDrawRow("fallback-6", "fallback-6", (13, 19, 25, 30, 42, 46)),
    CausalDrawRow("fallback-7", "fallback-7", (3, 17, 19, 31, 32, 33)),
    CausalDrawRow("fallback-8", "fallback-8", (1, 20, 26, 29, 38, 41)),
    CausalDrawRow("fallback-9", "fallback-9", (1, 25, 27, 32, 33, 49)),
)


@pytest.mark.parametrize("length", sorted(DONOR_GOLDENS))
def test_matches_executed_donor_golden(length: int) -> None:
    assert BigLottoFrontendSumRangeAdapter().get_one_bet(
        _history(length), LotteryType.BIG_LOTTO
    ) == (DONOR_GOLDENS[length], None)


def test_minimum_history_and_meaningful_window_boundary_are_explicit() -> None:
    adapter = BigLottoFrontendSumRangeAdapter()
    with pytest.raises(InsufficientHistory):
        adapter.get_one_bet((), LotteryType.BIG_LOTTO)
    assert adapter.get_one_bet(_history(9), LotteryType.BIG_LOTTO) == (
        DONOR_GOLDENS[9],
        None,
    )
    assert adapter.get_one_bet(_history(10), LotteryType.BIG_LOTTO) == (
        DONOR_GOLDENS[10],
        None,
    )


def test_frequency_ties_preserve_ascending_integer_key_order() -> None:
    history = (
        CausalDrawRow("tie-0", "tie-0", (10, 20, 30, 40, 45, 49)),
        CausalDrawRow("tie-1", "tie-1", (10, 20, 30, 40, 45, 49)),
    )
    assert BigLottoFrontendSumRangeAdapter().get_one_bet(
        history, LotteryType.BIG_LOTTO
    ) == ((10, 20, 30, 40, 45, 49), None)


def test_reachable_no_combination_fallback_matches_donor() -> None:
    assert BigLottoFrontendSumRangeAdapter().get_one_bet(
        FALLBACK_HISTORY, LotteryType.BIG_LOTTO
    ) == ((25, 26, 29, 32, 33, 42), None)


def test_edge_numbers_and_output_are_sorted_legal_and_deterministic() -> None:
    history = (
        CausalDrawRow("edge-0", "edge-0", (1, 2, 3, 4, 5, 6)),
        CausalDrawRow("edge-1", "edge-1", (44, 45, 46, 47, 48, 49)),
    )
    adapter = BigLottoFrontendSumRangeAdapter()
    first = adapter.get_one_bet_with_emission(history, LotteryType.BIG_LOTTO)
    second = adapter.get_one_bet_with_emission(history, LotteryType.BIG_LOTTO)
    assert first == second
    assert first.emitted_main_numbers == (1, 2, 3, 4, 5, 6)
    assert first.legal_main_numbers == (1, 2, 3, 4, 5, 6)
    assert first.special_number is None


def test_invalid_history_and_wrong_lottery_fail_closed() -> None:
    adapter = BigLottoFrontendSumRangeAdapter()
    invalid = (CausalDrawRow("bad", "bad", (1, 1, 2, 3, 4, 5)),)
    with pytest.raises(InvalidOutput):
        adapter.get_one_bet(invalid, LotteryType.BIG_LOTTO)
    with pytest.raises(UnsupportedLotteryType):
        adapter.get_one_bet(_history(1), LotteryType.DAILY_539)


def test_catalog_and_registry_add_exactly_one_online_identity() -> None:
    catalog = production_catalog()
    descriptor = catalog.get(STRATEGY_ID)
    assert [item.strategy_id for item in catalog].count(STRATEGY_ID) == 1
    assert descriptor.strategy_id == BigLottoFrontendSumRangeAdapter.strategy_id
    assert descriptor.strategy_name == BigLottoFrontendSumRangeAdapter.strategy_name
    assert descriptor.version == BigLottoFrontendSumRangeAdapter.strategy_version
    assert descriptor.lottery_types == (LotteryType.BIG_LOTTO,)
    assert descriptor.lifecycle_status is LifecycleStatus.ONLINE
    assert descriptor.executable is True
    assert descriptor.response_shape is ResponseShape.SINGLE_TICKET
    assert descriptor.native_ticket_count == 1
    assert descriptor.min_history == 1
    assert descriptor.adapter_path == (
        "lottolab.strategies.adapters.biglotto_frontend_sum_range:"
        "BigLottoFrontendSumRangeAdapter"
    )
    assert (
        "legacy_source_sha256:"
        "4941213e6c460e6a8bce50a42777e21018ed46e3a618d11bf26f05d3c5f5bee3"
        in descriptor.provenance
    )
    assert "legacy_symbol:SumRangeStrategy.predict" in descriptor.provenance
    assert "legacy_runtime:PredictionEngine.strategies.sum_range" in descriptor.provenance
    assert (
        "donor_execution:REVIVED_WITH_SYNCHRONOUS_STATISTICS_SERVICE_STUB_ISOLATED"
        in descriptor.provenance
    )
    assert ExecutableRegistry(catalog).load_adapter(STRATEGY_ID) is (
        BigLottoFrontendSumRangeAdapter
    )


def _request(history: tuple[CausalDrawRow, ...]) -> GenerateOneBetInput:
    return GenerateOneBetInput(
        strategy_id=STRATEGY_ID,
        lottery_type=LotteryType.BIG_LOTTO,
        history=history,
    )


def test_production_single_ticket_generation_path_is_reachable() -> None:
    result = build_production_generate_one_bet().execute(_request(_history(20)))
    assert result.status is GenerateOneBetStatus.OK
    assert result.numbers == DONOR_GOLDENS[20]
    assert result.special_number is None
    assert result.reason_code is None


def test_portfolio_path_rejects_single_ticket_identity() -> None:
    result = build_production_generate_portfolio().execute(_request(_history(20)))
    assert result.status is GeneratePortfolioStatus.WRONG_RESPONSE_PATH
    assert result.numbers is None
    assert result.reason_code is GeneratePortfolioReason.STRATEGY_IS_NOT_PORTFOLIO


def test_production_generation_never_opens_a_database(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def _forbidden_connect(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("Frontend Sum-range Strategy must not open a database")

    monkeypatch.setattr(sqlite3, "connect", _forbidden_connect)
    result = build_production_generate_one_bet().execute(_request(_history(20)))
    assert result.status is GenerateOneBetStatus.OK
    assert result.numbers == DONOR_GOLDENS[20]
